### ISSUE TITLE
math: add more Vec methods/operations

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#1003]
Check: Does our e.g. Vec4 type have these? If not implement them. Feel free to reference [this](https://github.com/greggman/wgpu-matrix/blob/main/src/vec4-impl.ts) in doing so.

```
min(a: Vec, b: Vec): Vec
max(a: Vec, b: Vec): Vec
minScalar(a: Vec, b: Vec): Scalar
maxScalar(a: Vec, b: Vec): Scalar
inverse(a: Vec) Vec
negate(a: Vec) Vec
```

**Comment by noisegul** [comment]
Would like to take a look at this.
