### ISSUE TITLE
Get ezpkg working with Mach

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#1005]
@mattnite has a very useful tool for Zig package development:

https://github.com/mattnite/ezpkg

But currently it doesn't work with Mach packages for various reasons, we need to get it working.

**Comment by mattnite** [comment]
I’ll try to find some time to investigate the issue soon, it’s been on my todo list for a while.

**Comment by slimsag** [comment]
Probably unnecessary now that Zig has file:// support we can use.
