### ISSUE TITLE
{mach,core}: windows builds failing currently

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#1012]
This is related to a regression in Zig / since we updated to the newer Zig version yesterday.

https://github.com/hexops/mach-core/actions/runs/6216642066/job/16870727695

**Comment by slimsag** [comment]
Temporary workaround:

You can build in WSL2 using `zig build -Dtarget=x86_64-windows-gnu` which will cross-compile for Windows. All the same commands will work since WSL can run native windows `.exe`s - just add `-Dtarget=x86_64-windows-gnu` to whatever command you want to run.

**Comment by slimsag** [comment]
This is fixed in the latest mach-core version d2b382d9698fc621d912ba1c693fe484d8e2178a
