### ISSUE TITLE
xcode-frameworks: add GameController, update to MacOSX14.0.sdk

### ISSUE THREAD

**Issue by mitchellh** [hexops/mach#1077]
My usage requires GameController.framework, I imagine this is interesting to Mach as well 😄 

Also, I recommend updating to MacOSX14.0.sdk, if you do you'll need to also add `Symbols.framework` since AppKit now depends on it.

**Comment by slimsag** [comment]
GameController -> indeed

> I recommend updating to MacOSX14.0.sdk

For which reason? I was under the impression usage of the higher SDK versions can trigger dependency on the higher macOS version in some cases.. maybe I'm wrong though

**Comment by mitchellh** [comment]
> For which reason? I was under the impression usage of the higher SDK versions can trigger dependency on the higher macOS version in some cases.. maybe I'm wrong though

They only do if you use features from newer versions. You can conditionally wrap stuff in runtime detection to avoid that. The reason is I use the new macOS 14 text carat features (only if running on macOS 14).

**Comment by mitchellh** [comment]
Oh I also use the new animated symbols, again only if macOS 14.

**Comment by slimsag** [comment]
Ah, you're right. Okay, sounds good

**Comment by slimsag** [comment]
@mitchellh fixed! feel free to file another issue if you run into anything else
