### ISSUE TITLE
Building mach on Mac OS fails with hash mismatch

### ISSUE THREAD

**Issue by djavorszky** [hexops/mach#1081]
### Steps to reproduce
1. Clone Mach (main branch)
2. Step into the cloned directory
3. `zig build`

### Result

```
zig build
Fetch Packages [2/7] mach_core... /Users/djavorszky/dev/mach/build.zig.zon:20:21: error: hash mismatch: expected: 12203bdeb8af9b1da2a521beafb51e3657e1c4f49b058cdd114f607b75dbb95ad306, found: 1220fa11a6465ba1641226e9e95ffedd7a792b7ea7d3374182b901c0e4630f71641a
            .hash = "12203bdeb8af9b1da2a521beafb51e3657e1c4f49b058cdd114f607b75dbb95ad306",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Additional information
1. `mach_core` has the same issue, but when fetching `mach_dusk`
2. Computer is MacBook Pro with an M1 Pro chip
3. `zig` was installed via `brew`

**Comment by slimsag** [comment]
Hello!

The main repository has an issue currently, but mach-core is promised to work.

Please make sure you are using a supported Zig version: https://machengine.org/about/zig-version/

The one provided by brew may not be sufficient, hash mismatch is one sign of this.

If you are using a Linux machine with btrfs filesystem (e.g. Fedora), you may need to set `ZIG_BTRFS_WORKAROUND=1` to workaround a bug in Zig / the Linux kernel.

Let me know if that helps.

**Comment by kamidev** [comment]
Hi! I also had problems building the latest stuff. 

The expected zig version (as indicated by the .zig-version file and recent commits) is 0.12.0-dev.1092+68ed78775. But the download link [he](https://machengine.org/about/zig-version/) currently points at an earlier version. Shouldn't that be updated in in sync with .zig-version?

**Comment by slimsag** [comment]
@kamidev yep, I've updated the website. In the future `.zigversion` and the website will always be in sync.

If anyone encounters more issues here, feel free to open a new issue.
