### ISSUE TITLE
gpu-dawn mach-core: ChildProcess.exec fails in zig 0.12.0

### ISSUE THREAD

**Issue by jmbert** [hexops/mach#1087]
ChildProcess.exec has been renamed to ChildProcess.run, causing errors in gpu-dawn and mach-core

**Comment by michal-z** [comment]
Fix is trivial `exec()` -> `run()`.

**Comment by slimsag** [comment]
Please make sure you are using a supported Zig version: https://machengine.org/about/zig-version/

**Comment by slimsag** [comment]
https://github.com/hexops/mach/issues/1093
