### ISSUE TITLE
mach-core hash mismatch on MacOS

### ISSUE THREAD

**Issue by genejo** [hexops/mach#1114]
Hi,

Sadly the mach-core examples don't seem to work out of the box on MacOS as specified here https://machengine.org/core/examples/ . Tried meddling with different url's & hashes, but failed to see anything build. Would you know which .url and .hash are correct for `mach-dusk` (where the error stems from) ?

```
> zig build run-triangle-msaa

Fetch Packages [5/7] mach_dusk... /Users/xxx/learn/mach-core/build.zig.zon:37:21: error: hash mismatch: expected: 1220d0bf732d8291b8629ce7e115efb6adef84dcc1218317ee0a89a6f1663153f2a9, found: 1220b2f1493dd897d7012a6abab22684114a3f57d38a2490f0d1d8a1f5cd54e125a1
            .hash = "1220d0bf732d8291b8629ce7e115efb6adef84dcc1218317ee0a89a6f1663153f2a9",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thanks.

**Comment by slimsag** [comment]
Hello! This is a symptom of using the wrong Zig version, since their hashing algorithm changed for packages in the past.

Make sure to use the version specified here: https://machengine.org/about/zig-version/

Let me know if that helps

**Comment by genejo** [comment]
Oh wow, that helps indeed, thank you so much! My version was too old and latest didn't work.. also I skipped the about page - will keep it in mind for the future.

Awesome!
