### ISSUE TITLE
core: hash mismatch on sysgpu

### ISSUE THREAD

**Issue by eightween** [hexops/mach#1124]
mach-core on https://github.com/hexops/mach-core/commit/90c927e20d045035152d9b0b421ea45db7e5569c has a hash mismatch on sysgpu https://github.com/hexops/mach-sysgpu/commit/e5682c4d05ab8f50defdf821be431eb7ead75111 causing a compilation build error:

```console
18@[redacted]:~/atlas/lib/mach-core$ zig build
Fetch Packages [5/7] mach_sysgpu... /home/18/[redacted]/lib/mach-core/build.zig.zon:37:21: error: hash mismatch: expected: 1220e011b9bb9e642b0a0434f7a30617cc12e2c8ea05af50d889f079ec531dc04512, found: 12203a1f1ca5fed1d103512acac0440e00bdc82d348cdf60de38a2a248d589a118d0
            .hash = "1220e011b9bb9e642b0a0434f7a30617cc12e2c8ea05af50d889f079ec531dc04512",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

this is on latest commit preventing being able to fully build mach-core

**Comment by slimsag** [comment]
Hello! As you can see the CI is testing `zig build` on each OS, and is passing with the commit you linked:

<img width="540" alt="image" src="https://github.com/hexops/mach/assets/3173176/593ecae8-9ba6-4fb7-8466-88763a16023b">

Most likely you are using an unsupported Zig version; see https://machengine.org/about/zig-version/

If you still run into issues after that, feel free to open a new issue or post in the discord and I can help debug.
