### ISSUE TITLE
all: eliminate `sdkPath`

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#1151]
`sdkPath` has become unnecessary since the day we switched to package manager

**Comment by slimsag** [comment]
Show me a usage of it that we can remove :) I already removed a ton of them, the ones that remain we can't remove for various reasons - or are in mach-gpu or mach-gpu-dawn which will go away.

**Comment by alichraghi** [comment]
ah cool. i mainly meant mach-gpu-dawn. closing now!

**Comment by slimsag** [comment]
Worth keeping open for the few that do remain for sure.
