### ISSUE TITLE
build problem only use mach-core: update to Zig 2024.5.0-mach, hit build problem

### ISSUE THREAD

**Issue by limitee** [hexops/mach#1216]
when update to Zig 2024.5.0-mach, I hit something strange: When I change something in a sub module, run zig build, will do nothing. This not happens when use 0.12. 

```
const ui_module = std.Build.Module.Import{
        .name = "ui",
        .module = b.createModule(.{
            .root_source_file = .{ .src_path = .{ .owner = b, .sub_path = "src/context/mod.zig" } },
        }),
    };

const crypto = try mach.CoreApp.init(b, mach_dep.builder, .{
        .name = "crypto",
        .src = "src/app.zig",
        .target = target,
        .optimize = optimize,
        .deps = &[_]std.Build.Module.Import{ zmath_module, zigimg_module, zul_module, service_module },
    });

crypto.module.addImport("ui", ui_module.module);
```

change something in ui module's source code. then run zig build, nothing happens.
when in 0.12, It will rebuild the poject.
And If not use the mach core, It will rebuild the project, too.

**Comment by slimsag** [comment]
You should migrate away from `CoreApp` / follow https://machengine.org/core/migrations/#machcore-migration-to-new-mach-module-system-2024-06-02
