### ISSUE TITLE
core: `printTitle` doesn't work on windows 11

### ISSUE THREAD

**Issue by nippi05** [hexops/mach#1242]
Hardware:

- 12th gen Intel(R) Core(TM) i7-1255U
- Intel(R) UHD Graphics

Software:

- Windows 11

`examples/core/triangle` doesn't change the window title neither does any other example. It's just "Mach core"

![image](https://github.com/user-attachments/assets/8e9fd5ef-19de-4f3d-9f33-c6077b85dcb5)

**Comment by nippi05** [comment]
Just checked `mach.core.printTitle` 😅. Should I keep this open?

**Comment by hordurj** [comment]
It is fixed in PR https://github.com/hexops/mach/pull/1241
