### ISSUE TITLE
Please don't throw an error on a newer Zig version

### ISSUE THREAD

**Issue by buzmeg** [hexops/mach#1263]
I can understand throwing an error on an older version, but please don't throw an immediate error on a newer version without at least trying to compile.  I tried to upgrade my Zig today and got:

```build.zig:38:9: error: unsupported Zig version (0.14.0-dev.1410+13da34955). Required Zig version 2024.5.0-mach: https://machengine.org/about/nominated-zig/#202450-mach
        @compileError(std.fmt.comptimePrint("unsupported Zig version ({}). Required Zig version 2024.5.0-mach: https://machengine.org/about/nominated-zig/#202450-mach", .{builtin.zig_version}));
```

Everything may very well compile (I'm only using mach-freetype), but I can't even *try* without pulling in the project and modifying the build.zig and ...

I'm fine with throwing a warning if your compiler is newer than expected.

I understand not taking bug reports on non-nominated versions.  However, this kind of behavior in the build.zig strongly discourages people from relying on external packages.

**Comment by slimsag** [comment]
Working as intended.

We support a single Zig version, if you aren't using a supported version then you should be aware of it.

If you want to try the package with an unsupported version, feel free to fork it.

You can learn more of the reasoning behind this here: https://machengine.org/docs/nominated-zig/

**Comment by buzmeg** [comment]
Sorry, it was glfw and not freetype causing the issue and you're not maintaining glfw anymore.  My apoligies for the noise.

I will excise mach-glfw since it's not being maintained.

Thanks.
