### ISSUE TITLE
Core: build succeeds on linux but fails at runtime

### ISSUE THREAD

**Issue by Tatskaari** [hexops/mach#1265]
Linux support has been removed in this commit: 
https://github.com/hexops/mach/commit/17450fde65289da7ac01ba174c26687fc9691182 

It's not clear when building on linux that core is no longer supported. Should we fail fast here?

**Comment by joshua-holmes** [comment]
Since you posted this, Linux support has been added again on Wayland. I am working on X11 support soon as well :)

**Comment by joshua-holmes** [comment]
@Tatskaari after [this PR](https://github.com/hexops/mach/pull/1282) is pulled in, X11 will be supported as well, though some features are missing. However there is a log message that is sent that lists the missing features.
