### ISSUE TITLE
website: contributors generated list is poor, doesn't work sometimes

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#138]
@AliChraghi reported the contributors image on the homepage doesn't load in his location:

https://github.com/hexops/mach/pull/128#issuecomment-997431462

We are using contrib.rocks currently, e.g. https://contrib.rocks/image?repo=hexops/mach

This is different from the list of sponsors, which is generated as a separate image per sponsor using this: https://github.com/hexops/hexops.com/blob/main/.github/workflows/sponsors.yml

Maybe just switch to a manually curated list or something. Not sure.

**Comment by slimsag** [comment]
Oh, https://remarkablemark.org/blog/2019/10/17/github-contributors-readme/ does look better

Should just be able to swap that out in this page: https://github.com/hexops/hexops.com/blob/main/content/mach.md

**Comment by AliChraghi** [comment]
https://remarkablemark.org/blog/2019/10/17/github-contributors-readme/ requires ***opencollective*** account for project. i did't find any solution to replace it. i think it's ok to close this

**Comment by iddev5** [comment]
Contributors list can be fetched from raw API request ``GET https://api.github.com/repos/hexops/mach/size`` or using the REST or GraphQL API, but that would mean doing everything from scratch :sweat_smile:

**Comment by AliChraghi** [comment]
good idea. we just fetch it every month/week/day/etc idk. and put it into site

**Comment by slimsag** [comment]
For sponsors I have a (terrible) GitHub action that runs on each push (so it updates whenever I push a commit to the website), it uses the GitHub GraphQL API and does a dumb find/replace of a `<!-- marker -->` in the file

https://github.com/slimsag/github-sponsors-readme-action

For example it made this change to the file: https://github.com/hexops/hexops.com/commit/cb79b51be124118b2403f4f993f3b7f051f0b0f6#diff-ed7002b439e9ac845f22357d822bac1444730fbdb6016d3ec9432297b9ec9f73

There is another GitHub action which handles the commit/push, so really just need a way to update the file.

But honestly, also happy to maintain the list manually or something - I doubt we will have too many contributors in the near future.

**Comment by AliChraghi** [comment]
i think currently it's better to continue using `contrib.rocks` because the low amount of contributors. but in future we can do it manually or using shell script and as you said refresh it with github-actions

**Comment by slimsag** [comment]
I fixed this with a manually updated list. The metric I am using for inclusion right now is in this order:

1. Contributors with >500 lines added, in order shown [at this page](https://github.com/hexops/mach/graphs/contributors?from=2021-07-04&to=2022-05-31&type=a).
1. If less than 500 lines added, anyone who has contributed an example/demo.

May revise over time.
