### ISSUE TITLE
Pull request #136 overwrites #72

### ISSUE THREAD

**Issue by hasklix** [hexops/mach#149]
GLFW has yet to merge [this pull request](https://github.com/glfw/glfw/pull/1989) and the version bump from #136 has overwritten #72 (`x11_window.c` line 1286).

**Comment by AliChraghi** [comment]
@slimsag Isn't it better to apply same change by sending PR to glfw instead of modifying upstream?

**Comment by iddev5** [comment]
If it is not merged to upstream soon, then I think it would make sense to have a solution in the form of a patch which gets auto merged with ``update-upstream.sh``

**Comment by AliChraghi** [comment]
or maybe add a note to README.
i think at least someone remember this when we are updating glfw

**Comment by iddev5** [comment]
Maintainer info should not be added to README.md which is meant for end users

**Comment by slimsag** [comment]
@hasklix Merged the fix, thanks for reporting this!

Let's continue discussion of how to prevent this from regressing in the future in #95
