### ISSUE TITLE
Make mach/gpu consumable as a separate repository

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#189]
If you want to use `mach/gpu` (the WebGPU bindings for Zig) without anything else we're building (the ECS and numerous other things in the future) you should be able to.

We'll publish the `gpu/` subdirectory of this repo as a separate repo github.com/hexops/mach-gpu, similar to how `glfw/` is [available here](github.com/hexops/mach-glfw) and `gpu-dawn/` is [available here](github.com/hexops/mach-gpu-dawn).

Probably desirable for integration into e.g. https://github.com/michal-z/zig-gamedev too.

**Comment by johanfforsberg** [comment]
Does the "gpu" part necessarily depend on glfw?

**Comment by slimsag** [comment]
mach/gpu depends on mach/gpu-dawn, which depends on mach/glfw for now. Dawn exposes some GLFW-specific integration code that is used for the OpenGL backend, currently, but they're moving to a surface-based API (which is available for all other backends except opengl.)

So the answer is: today yes, long-term, no.
