### ISSUE TITLE
Building the example

### ISSUE THREAD

**Issue by p0nce** [hexops/mach#193]
I tried to be as naive as possible and build the examples using the command from the website.

![image](https://user-images.githubusercontent.com/1067485/160308372-6fbf563c-7b2d-4179-919c-f20dbfd1ad0b.png)

What to do?

**Comment by p0nce** [comment]
![image](https://user-images.githubusercontent.com/1067485/160308443-2c2d4902-5b85-41c2-a9a0-0374ed46a50a.png)

**Comment by slimsag** [comment]
Hi there! Thanks for trying it out. It looks like you don't have symlink support enabled in Windows, some solutions are described here: https://github.com/hexops/mach/blob/main/doc/known-issues.md#windows-file-not-found

**Comment by p0nce** [comment]
I've stopped trying, but linking the known issue from the homepage would help, since I hadn't found this page. afaik, any windows developer trying your homepage solution will hit this.

**Comment by slimsag** [comment]
Thanks, it is linked, but I guess easy to miss.
