### ISSUE TITLE
gpu-dawn: linux aarch64 support

### ISSUE THREAD

**Issue by LaPingvino** [hexops/mach#194]
While trying to run `zig build run-example` on Debian ARM64 in a Chromebook Crostini VM I get:

```
error: gpu-dawn binaries for aarch64-linux.5.10.92...5.10.92-gnu.2.33 not available.
error: -> open an issue: https://github.com/hexops/mach/issues
error: -> build from source (takes 5-15 minutes):
error:        use -Ddawn-from-source=true or set `Options.from_source = true`
```

and adding -Ddawn-from-source=true to this command or trying to set from_source to true any other way doesn't fix it.

**Comment by LaPingvino** [comment]
Update: when going directly in the libs directory version of mach-gpu-dawn, it does accept the dawn-from-source option as in `zig build -Ddawn-from-source=true`, it's just not passed on from running the example. Now sleep, will try more later.

**Comment by mitchellh** [comment]
For step one: https://github.com/mitchellh/mach-sdk-linux-aarch64

**Comment by mitchellh** [comment]
Fwiw, with the two steps already taken, you can now run `zig build run-dawn-example -Ddawn-from-source=true` in the `gpu-dawn` directory and this all just works on aarch64 Linux. I tested locally. Hopefully binary builds can come though :)

**Comment by slimsag** [comment]
Plan for binary builds: GitHub actions doesn't have ARM runners, but we can just cross-compile. Should be easy, I'll get this working within a few days.

**Comment by kamidev** [comment]
There is an open PR which may solve the atomics issues with linux aarch64: https://github.com/ziglang/zig/pull/11828#. Zig core team has been busy with other linker-related work lately, but hopefully it will be merged eventually.

**Comment by slimsag** [comment]
In theory this probably all works now, but I don't think anyone has tested it / confirmed it does.

Getting an aarch64-linux machine to test on has been very annoying, I had bought a ROCK pi 5B for this but just last week it randomly died and I don't know why (nvme failure perhaps.)

If someone can test it works or not, that'd be helpful information in pushing support of this along.

**Comment by slimsag** [comment]
The way to test:

```
git clone https://github.com/hexops/mach
cd mach/libs/gpu
zig build run-example
```

**Comment by alichraghi** [comment]
added to #811

**Comment by LaPingvino** [comment]
with 10.1 I get `/home/ikojba/mach/libs/gpu/build.zig:7:21: error: root struct of file 'std' has no member named 'Build'`

**Comment by alichraghi** [comment]
mach tracks master so `0.10.1` shouldn't work at all. all you have to do is changing `std.builtin.Version` to `std.SemanticVersion` in this [line](https://github.com/hexops/mach/blob/4430ce08ec4566d247a1db553135270f19d1f15e/libs/gpu-dawn/sdk.zig#L225)
```diff
-- const min_available = std.builtin.Version{ .major = 12, .minor = 0 };
++ const min_available = std.SemanticVersion{ .major = 12, .minor = 0 };
```

**Comment by LaPingvino** [comment]
Now just some "Missing struct field: .patch" errors...

**Comment by alichraghi** [comment]
`std.SemanticVersion{ .major = 12, .minor = 0, .patch = 0 };`

**Comment by LaPingvino** [comment]
After fixing #811 this seems to work flawlessly :D

**Comment by slimsag** [comment]
Works as in you ran on an arm device and saw graphics?

**Comment by LaPingvino** [comment]
Yes, exactly that!

On June 21, 2023 at 4:58 GMT, Stephen Gutekanst ***@***.***> wrote:

Works as in you ran on an arm device and saw graphics?
