### ISSUE TITLE
precompiled gpu-dawn for macos 10.x 

### ISSUE THREAD

**Issue by colemanbroad** [hexops/mach#199]
Just curious if macos 10.x (Catalina) will get precompiled gpu-dawn binaries at some point.
Build from source works with flag if i'm in `mach/gpu-dawn/`, which is awesome!
mach is going to be a lot of fun :)

```
> zig build run-example
error: gpu-dawn binaries for x86_64-macos.10.15.7...10.15.7-gnu not available.
error: -> open an issue: https://github.com/hexops/mach/issues
error: -> build from source (takes 5-15 minutes):
error:        use -Ddawn-from-source=true or set `Options.from_source = true`
```

**Comment by slimsag** [comment]
I'll close this in favor of #202 - the short answer is I can't support macOS 10, it's too old and I don't have the bandwidth to support it. It's version of Metal is also older and imposes some limitations you might not want. Upgrading the OS is the right thing to do.

For what it's worth, I imagine macOS 11 will be supported for a longer duration of time. I just have to draw a line in the sand somewhere (unfortunately!) - sorry if this is not what you wanted to hear!

**Comment by colemanbroad** [comment]
no worries 👍  fully understand and support this.
