### ISSUE TITLE
Window.setIcon tests failing

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#20]
Probably on all window managers, maybe on Windows too?

> In my case xfce4 (it fails on my Ubuntu based distro called Linux Lite and the Garuda/Arch distro).

I can reproduce at least on Ubuntu 20.04 vanilla.

**Comment by slimsag** [comment]
@Avokadoen I thought you might like to know, this turned out to be much crazier than I thought :) https://devlog.hexops.com/2021/perfecting-glfw-for-zig-and-finding-undefined-behavior

**Comment by Avokadoen** [comment]
Great article! Always fun to read about stuff like this. I'm impressed with your deduction skills 😁

**Comment by Avokadoen** [comment]
My project is now using the master of mach-glfw. It was pretty painless porting at this point!

**Comment by slimsag** [comment]
Awesome!

**Comment by wilsonk** [comment]
I realize this is closed now, but I just wanted to say kudos on getting to the bottom of that silly bug Stephen. I didn't get so deep in the weeds as to break out IDA Pro :)  I love that Zig is catching this type of thing...after 6 years of, I would assume, extensive use in many situations! Great stuff.

**Comment by slimsag** [comment]
Thanks so much for the kind words @wilsonk, I'm glad to hear you like it :) and thanks for sponsoring me. Hopefully much more than a little bug fix to come soon ;)
