### ISSUE TITLE
gpu-dawn: prioritize source builds if available

### ISSUE THREAD

**Issue by silversquirl** [hexops/mach#207]
If Dawn has previously been built from source, it would be nice if that build was automatically used without needing to specify `-Ddawn-from-source` in future; currently the build script will download a binary release if you don't specify that option.

**Comment by slimsag** [comment]
I'm not sure there's a sane way to do this.

It sounds like you want it to be the case that if you've previously specified `-Ddawn-from-source=true`, then it always uses that option in the future. I feel like a CLI flag like that retaining that as state going forward is strange and could be quite confusing.

Maybe it just needs to be more apparent how to choose the default for _your_ project, via specifying the `.from_source = true` `Option` to gpu-dawn? Have you found that already and don't find that suitable in this case?

**Comment by silversquirl** [comment]
It's a little more specific than that - if there's a build for *the current commit* then it'd use that, but if you then upgrade mach it should download the new version.

Thinking about it further, I agree that is pretty weird and confusing though, and the only real case where it's useful (at least to me) is when making changes to mach's dawn fork.
