### ISSUE TITLE
mach: default to high-power adapters; let user choose

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#216]
https://matrix.to/#/!bIJeTLtOHucXQpqIcH:matrix.org/$u4RlZPTkXo8VrObrMSY6rSppArpToyK6ZRIO-F8PBvk?via=matrix.org&via=mozilla.org&via=pythons.space

<img width="902" alt="image" src="https://user-images.githubusercontent.com/3173176/163023111-02885d2d-69af-4b07-aeea-db8f25b59e9c.png">

**Comment by d3m1gd** [comment]
it would be good to blacklist known bad backend implementations.

in linux vulkan drivers for old GPUs exist as software-only mesa's `llvmpipe` implementation, while at the same time fully accelerated OpenGL implementation might be available.

**Comment by Luexa** [comment]
+1 for this issue. For a project I'm working on, I'm experimenting with some cleaner ways to expose key Dawn Native functions to Zig, and I've been trying to clean up the `sample_utils.zig` file as well (currently I've just done a hack that compares int representation of enum to prioritize high-power adapters, but I want a cleaner solution). Once I have something that works for my project I will likely make a PR to this repo :)
