### ISSUE TITLE
MacOS sdk query panic

### ISSUE THREAD

**Issue by wilsonk** [hexops/mach#22]
Hey @slimsag,

When building the test from the root directory for MacOS on Linux...if I just hit 'enter' to accept the seeming 'Y' default for the MacOS SDK install question from build.zig:336, then I get an integer overflow error and stack trace from zig. Simple fix, I suppose, but I wasn't sure if you wanted to force a user to actually type some answer there for legal reasons, so I will leave it up to you. I didn't test on Windows

**Comment by slimsag** [comment]
Whoops! Looks like a regression introduced when I added the Windows support, I definitely want just pressing enter to make it continue :)

Feel free to send a PR to fix if you like, otherwise I'll get to this a bit later next week sometime!
