### ISSUE TITLE
Looks like ubsan catches an issue in dawn - crash in debug config (linux, vulkan)

### ISSUE THREAD

**Issue by michal-z** [hexops/mach#221]
Works fine in release - I think we could consider disabling sanitizers when building dawn or spend some time debugging.

![image](https://user-images.githubusercontent.com/11540112/163242612-518ded15-fc97-43d9-9f70-51a6231a804f.png)

**Comment by michal-z** [comment]
I can confirm that building dawn from source with sanitizers disabled (`-fno-sanitize=undefined`) fixes the crash.

**Comment by michal-z** [comment]
Found the issue in dawn. ubsan is complaining about memcpy being called with size 0.

The fix is to check `dynamicOffsetCount` before calling `SetDynamicOffsets`.

In `src/dawn/native/BindGroupTracker.h` line 58:

Current code:
```cpp
SetDynamicOffsets(mDynamicOffsets[index].data(), dynamicOffsetCount, dynamicOffsets);
```

Fixed code:
```cpp
if (dynamicOffsetCount > 0) {
    SetDynamicOffsets(mDynamicOffsets[index].data(), dynamicOffsetCount, dynamicOffsets);
}
```

**Comment by Kangz** [comment]
Can you file an issue on crbug.com/dawn ? :)

**Comment by michal-z** [comment]
> Can you file an issue on crbug.com/dawn ? :)

https://bugs.chromium.org/p/dawn/issues/detail?id=1371

**Comment by silversquirl** [comment]
See hexops/dawn#9

**Comment by michal-z** [comment]
@slimsag Can you please merge above PR? This issue affects zig-gamedev project -- all Linux users get a crash in WebGPU imgui renderer. Thanks!

**Comment by slimsag** [comment]
Should be able to merge+release the temporary patch in the next few days (a bit swamped right now due to holiday)

Will also make sure we send a CL upstream to Dawn for this change.

**Comment by michal-z** [comment]
Sounds good, thanks! Do you also plan to fetch the latest code from Dawn and create another `generated-*` branch?

**Comment by slimsag** [comment]
Yes

**Comment by slimsag** [comment]
Should be fixed now (sorry for closing prematurely!) - fixed in https://github.com/hexops/mach/commit/c9ac61c1c4093e4b4b524c6b5dd7ca4f2fc6e5b4

Feel free to file a new issue if you continue to run into issues.
