### ISSUE TITLE
core: examples: add a few more WebGPU examples

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#230]
I'd like to end up with most interesting WebGPU examples out there ported over for people to easily use/consume from Zig.

If you'd like to port one of these examples over (or come up with your own WebGPU example), feel free to do so and send a PR / post here! This is a tracking issue for exactly that.

You can use this as a template for where to put the code: https://github.com/hexops/mach/pull/227

* Examples we should port over from https://github.com/austinEng/webgpu-samples/tree/main/src/sample:
  * [x] boids
  * [x] [deferredRendering](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/deferredRendering)
  * [x] [fractalCube](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/fractalCube)
  * [x] [helloTriangleMSAA](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/helloTriangleMSAA)
  * [x] [imageBlur](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/imageBlur)
  * [x] [instancedCube](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/instancedCube)
  * [ ] [particles](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/particles)
  * [ ] [reversedZ](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/reversedZ)
  * [x] [rotatingCube](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/rotatingCube)
  * [ ] [shadowMapping](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/shadowMapping)
  * [x] [texturedCube](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/texturedCube)
  * [x] [twoCubes](https://github.com/austinEng/webgpu-samples/tree/main/src/sample/twoCubes)
* Many from https://github.com/samdauwe/webgpu-native-examples can be ported over, too.

**Comment by johanfforsberg** [comment]
Guess we can check off the "instancedCube" box due to #246. Also there is a "two-cubes" example already.

**Comment by slimsag** [comment]
https://github.com/hexops/mach/pull/410 brings the image-blur example

**Comment by alichraghi** [comment]
map-async added with #414
