### ISSUE TITLE
C++ coding for university

### ISSUE THREAD

**Issue by BaraAlqady123** [hexops/mach#243]
#include<iostream>
#include<cmath>
#include<string>
using namespace std;
class math{
 double a,p;
 public:
 double pow(double x,double y){
     a=x;
     p=y;
     
         
     double z=1;
     for(double i=0;i<y;i++)
     z*=a;
     return z;}
     double Sqrt(double x){
         
         return sqrt(x);
         }
    double max(double x, double y){
        if(x>=y)
        return x;
        else return y;}
        double max(double x, double y, double z){
            double m=max(x,y);
            if(z>=m)
            m=z;
            return m;}
double max(double x, double y, double z, double n){
 double m=max(x,y,z);
 if(n>m)
 m=n;
 return m;}
 double max (double x, double y, double z, double n, double s){
   double m=max(x,y,z,n);
   if(s>m)
   m=s;
   return m;}  
    
  double max (double x, double y, double z, double n, double s, double i){
   double m=max(x,y,z,n,s);
   if(i>m)
   m=i;
   return m; } 
    double max (double x, double y, double z, double n, double s, double i, double b){
  double m=max(x,y,z,n,s,i);
   if(b>m)
   m=b;
   return m; }
     double max (double x, double y, double z, double n, double s, double i, double b, double c){
   double m=max(x,y,z,n,s,i,b);
   if(c>m)
   m=c;
   return m;}     
    double max (double x, double y, double z, double n, double s, double i, double b, double c, double d){
   double m=max(x,y,z,n,s,i,b,c);
   if(d>m)
   m=d;
   return m; }
    double max (double x, double y, double z, double n, double s, double i, double b, double c, double d, double e){
   double m=max(x,y,z,n,s,i,b,c,d);
   if(e>m)
   m=e;
   return m;  }  
    //min functions
    double min(double x, double y){
        double m=x;
        if(y<m)
        m=y;
        return m; }
        double min(double x, double y, double z){
            double m=min(x,y);
            if(z<m)
            m=z;
            return m;  }
double min(double x, double y, double z, double n){
 double m=min(x,y,z);
            if(n<m)
            m=n; 
             return m;}
 double min(double x, double y, double z, double n, double s){
   double m=min(x,y,z,n);
            if(s<m)
            m=s;
   return m; }  
    
  double min (double x, double y, double z, double n, double s, double i){
   double m=min(x,y,z,n,s);
            if(i<m)
            m=i;
   return m;} 
    double min (double x, double y, double z, double n, double s, double i, double b){
   double m=min(x,y,z,n,s,i);
  if(b<m)
            m=b;
   return m;}
     double min (double x, double y, double z, double n, double s, double i, double b, double c){
   double m=min(x,y,z,n,s,i,b);
            if(c<m)
            m=c;
   return m;}     
    double min (double x, double y, double z, double n, double s, double i, double b, double c, double d){
   double m=min(x,y,z,n,s,i,b,c);
            if(d<m)
            m=d;
   return m;}
    double min(double x, double y, double z, double n, double s, double i, double b, double c, double d, double e){
   double m=min(x,y,z,n,s,i,b,c,d);
            if(e<m)
            m=e;
   return m;}
    //total
double total (double x){
    double m=0;
    for(int i=x;i>=1;i--)
    m+=i;
    return m;}
    //mult function
    double mult(double n){
double m=1;
for(int i=n;i>=1;i--)
 m*=i;
 return m;}
double avg(double x, double y){
 return x/y;}
 float fabs(float x){
   if(x>=0)
   return x;
   else return x*-1;}
   int abs(int x){
     if(x>=0)
     return x;
     else return x*-1;} 
  double ceil(double x){
      return x+0.01;}
    double sum(double x, double y){
        double m=x+y;
        return m;}
      double sum(double x, double y, double z){
          double m=sum(x,y)+z;
         return m;}
   double sum(double x, double y, double z, double a){
          double m=sum(x,y,z)+a;
         return m;}
         double sum(double x, double y, double z, double a, double b){
          double m=sum(x,y,z,a)+b;
         return m;}
         double sum(double x, double y, double z, double a, double b, double c){
          double m=sum(x,y,z,a,b)+c;
         return m;}
         double sum(double x, double y, double z, double a, double b, double c, double d){
          double m=sum(x,y,z,a,b,c)+d;
         return m;}
         double sum(double x, double y, double z, double a, double b, double c, double d, double e){
          double m=sum(x,y,z,a,b,c,d)+e;
         return m;} 
         double sum(double x, double y, double z, double a, double b, double c, double d, double e, double f){
          double m=sum(x,y,z,a,b,c,d,e)+f;
         return m;}
         double sum(double x, double y, double z, double a, double b, double c, double d, double e, double f, double g){
          double m=sum(x,y,z,a,b,c,d,e,f)+g;
         return m;}
    int mod(int x, int y){
     int m;
      m=x%y;
        return m;  
    }
 }; 

class university{
  private:
  struct student{
    string id,name;
    int mobile,numOfDepart,age;
    float avg,total,mark[6];
    student*right,*left;
    student (string i,string n,int m,int numOd,int ag,float to,float av){
        id=i;
        name=n;
        mobile=m;
        numOfDepart=numOd;
        age=ag;
        avg=av;
        total=to;
        right=NULL;
        left=NULL;
        }
    
    };
    struct teacher {
        string id,name;
        int mobile,age,numOfc,numOfd,num;
        float salary;
        teacher*right,*left;
        teacher (string n,string i,int nu,int mo,int ag,int noc,int nod,float sal){
         id=i;
         name=n;
         mobile=mo;
         age=ag;
         numOfc=noc;
         numOfd=nod;
         num=nu;
         salary=sal;
         right=NULL;
         left=NULL;}
            
        };
    struct course {};
    struct employees {};
    struct department{};
    
     student*root=NULL;
     teacher*root1=NULL;
     employees*root2=NULL;
     department*root3=NULL;
     public:
     void setStudentInfo(string i,string n,int m,int numOd,int ag,float to,float av){
     student*newstudent=new student(i, n,m,numOd, ag,to,av);
     if(root==NULL){
       root=newstudent;
       return;}
     student*temp=root;
     student*parent;
     while(temp!=NULL){
        parent=temp;
        if(to<=temp->total)
        temp=temp->left;
        else temp=temp->right; 
     }
     if(to<=parent->total)
     parent->left=newstudent;
     else parent->right=newstudent;
  }
  double maxS(){
     if(root==NULL)
     return-1;
     else{
         student*temp=root;
         while(temp->right!=NULL)
         temp=temp->right;
         return temp->total;
     }
  }
     void setTeacherInfo(){}
     void setCourseInfo(){}
     void setEmployeeInfo(){}
     void setDepartInfo(){}
    
    
    };

//+(((())))

int main(int argc, char *argv[])
{math m;
university u;
u.setStudentInfo("20220043","AL_Bara.a Amin AL_Qady",713748779,4,23,m.sum(99,96,97,91,99,98),m.avg(u.maxS(),6));
u.setStudentInfo("20220043","AL_Bara.a Amin AL_Qady",713748779,4,23,m.sum(99,99,97,91,99,98),m.avg(u.maxS(),6));

double x=m.avg(u.maxS(),6);
cout<<x;	
}

**Comment by slimsag** [comment]
LGTM, approved. You get an A++.

I can't lie, though, this part makes me question reality:

```
double min(double x, double y, double z, double n, double s, double i, double b, double c, double d, double e)
```

Cheers :)

**Comment by BaraAlqady123** [comment]
> LGTM, approved. You get an A++.
> 
> I can't lie, though, this part makes me question reality:
> 
> ```
> double min(double x, double y, double z, double n, double s, double i, double b, double c, double d, double e)
> ```
> 
> Cheers :)

😅
