### ISSUE TITLE
Running individual example causes it to rebuild everytime

### ISSUE THREAD

**Issue by iddev5** [hexops/mach#265]
Bug caused by https://github.com/hexops/mach/pull/259

When an individual example is run, say ``zig build run-example-triangle``, it is being forced to rebuilt every time despite it being already install/in latest state.

**Comment by iddev5** [comment]
This could be a compiler bug because I have a project with similar changes as #259 and it works completely fine.

**Comment by InKryption** [comment]
Is the behaviour the same on both Linux and Windows?

**Comment by iddev5** [comment]
I can only test on Linux.

**Comment by slimsag** [comment]
Can you try wiping out `zig-cache`? I'd be curious if it's a bug in zig-caching behavior

**Comment by iddev5** [comment]
Yeah that was it. It's strange that it happened to two copies of Mach for me. But I don't think there is a solid repro for it.
