### ISSUE TITLE
Mach glfw build.zig is out of sync

### ISSUE THREAD

**Issue by Avokadoen** [hexops/mach#266]
Seems like update https://github.com/hexops/mach/commit/45708383044ed88401cad6f4d275dbb057023446 is not synced in mach-glfw. 

Is this a bug, or normal delay in the CI?

**Comment by slimsag** [comment]
Sorry about that. The CI was failing to push to the subrepo.

(For context, when we change any files in the `.github` actions yaml, I have to manually run `./dev/push-subrepos.sh` because GitHub has a security measure that prevents any action from modifying an action file.)

Should be in sync now!

**Comment by Avokadoen** [comment]
Thanks for the fix 😍
