### ISSUE TITLE
gpu: ptr accesses should have more clear 'needs a slice' error messages

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#278]
Someone in Matrix asked:

> So texture data must be some kind of structure with a ptr field?

```
./libs/mach/gpu/src/Queue.zig:73:40: error: no field named 'ptr' in '*const [129600]u8'
        @ptrCast(*const anyopaque, data.ptr),
```

We should check the type at comptime and throw a more clear error (expected a slice)

**Comment by alichraghi** [comment]
do u approve this error message?
```rs
expected type []const u8, but got type [*]const u8
```

**Comment by slimsag** [comment]
@alichraghi that looks great to me
