### ISSUE TITLE
gpu-dawn binaries for Mac not available for latest zig

### ISSUE THREAD

**Issue by kamidev** [hexops/mach#292]
Zig 0.10 has changed the Darwin default ABI from "gnu" to "none", with this breaking PR: https://github.com/ziglang/zig/pull/11684. As a consequence, the expected gpu-dawn binaries currently does not exist for Mac users. 

Below an example using zig-gamedev. The problem is general, though.

```
➜  zig-gamedev git:(main) rm -rf git-cache; stage1 build
error: gpu-dawn binaries for aarch64-macos.12.4...12.4-none not available.
error: -> open an issue: https://github.com/hexops/mach/issues
error: -> build from source (takes 5-15 minutes):
error:        use -Ddawn-from-source=true or set `Options.from_source = true`
...
```
Building from source still works as expected.

**Comment by slimsag** [comment]
Thanks for filing, we're not yet up-to-date with that Zig version. We generally try to track latest nightly, but not always up to date. You can find the latest supported version Mach tracks in the CI config here:

https://github.com/hexops/mach/blob/f3e2b8b74c38f829e5717a75f6a07017ab6b8872/.github/workflows/ci.yml#L94

I'll leave this issue open until we do update.

**Comment by slimsag** [comment]
This is fixed, and you can now find the version of Zig we test with here: https://github.com/hexops/mach#supported-zig-version

Should be easier for us to keep up to date in the future, too.

Let me know if you run into any trouble.

**Comment by kamidev** [comment]
Works like a charm! We just changed zig-gamedev to use the right Mac binaries. Thanks a lot.
