### ISSUE TITLE
Mac M1 / aarch64 support 

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#3]
Currently not possible due to GitHub actions not having M1-based runners: https://github.com/actions/virtual-environments/issues/2187

Considering getting an M1 device for this.

**Comment by wilsonk** [comment]
Hey slimsag, I have an M1 here (and Win10-x64_64 and Linux-x86_64) with some spare cycles, and I like what you are doing here, so I decided to build mach and test it out a little. 

_______________________________________________________________________________
macOS-aarch64 -> macOS-aarch64  --  all tests in glfw pass and test window works
macOS-aarch64 -> macOS-x86_64  -- all tests in glfw pass and test window works

macOS-aarch64 -> Linux-x86_64 -- compilation errors with 
```
error(compilation): clang failed with stderr: In file included from /Users/wilsonk/mach/glfw/upstream/glfw/src/osmesa_context.c:34:
/Users/wilsonk/mach/glfw/upstream/glfw/src/internal.h:194:3: error: "No supported window creation API selected"
/Users/wilsonk/mach/glfw/upstream/glfw/src/internal.h:357:5: error: type name requires a specifier or qualifier
/Users/wilsonk/mach/glfw/upstream/glfw/src/internal.h:359:5: error: type name requires a specifier or qualifier
... PLUS many, many more
```

macOS-aarch64 -> Win-x86_64 -- same compilation errors as above.
iOS is the same again.
_______________________________________________________________________________
Linux-x86_64 -> Linux-x86_64 -- same errors as above
Linux-x86_64 -> macOS-x86_64 -- test window works
Linux-x86_64 -> macOS-aarch64 -- test window works
Linux-x86_64 -> iOS -- same errors as above
_______________________________________________________________________________
Win-x86_64 -> Win-x86_64 -- same errors as above
Win-x86_64 -> macOS-x86_64 -- build downloads the SDK and then just says 'error: Unexpected' and the command line for the compilation
Win-x86_64 -> macOS-aarch64 -- build downloads the SDK and then just says 'error: Unexpected' and the command line for the compilation
Win-x86_64 -> iOS -- same errors as above
_______________________________________________________________________________

Anyways, I just thought I would let you know that at least the cross compiled macOS-x86_64 version compiles/runs out of the box, and a couple of the Linux versions also cross compile and work. Anything else I can do?

I also looked at starting a native github CI runner on this M1 but it is still in development apparently (waiting on .NET support, I think)?

**Comment by slimsag** [comment]
Very cool @wilsonk ! I appreciate it :) You've actually tipped me over the edge, though, and so today I bought an M1 to test things on (and maybe set up a github CI runner on later.)

how did you test iOS cross compilation out of curiosity? I hadn't found info on zig support for that as a target yet

**Comment by wilsonk** [comment]
Lol, at this rate everyone is going to have an M1 @slimsag!

I actually didn't get any tests or anything running for the iOS target (I do have a few devices running iOS that I could/would test on though). I just tried the compilation with target 'aarch64-ios' and it exited quickly with 'no supported window creation API...' like above.

I think that someone got some sort of iOS output working in issue #5145 of the zig repo, and it could probably be done more easily now that Kubkon has the Zig linker working so well on Mac.

With the two patches I posted on the other issues, the errors above will disappear...at least for native Linux and Win10 x86_64. I haven't tested with cross compiling yet, but hopefully I can get to it tomorrow.

**Comment by slimsag** [comment]
Seems like trying to compile for `-Dtarget=aarch64-macos` without xcode installed (i.e. using the SDKs only) produces:

```
zig build test -Dtarget=aarch64-macos 

error(compilation): clang failed with stderr: In file included from /Users/slimsag/Desktop/hexops/mach/glfw/upstream/glfw/src/monitor.c:30:
In file included from /Users/slimsag/Desktop/hexops/mach/glfw/upstream/glfw/src/internal.h:49:
/Users/slimsag/Desktop/hexops/mach/glfw/upstream/glfw/src/../include/GLFW/glfw3.h:103:10: fatal error: cannot open file '/Users/slimsag/Desktop/hexops/mach/glfw/upstream/glfw/include/stddef.h': No such file or directory
```

It looks like the libc headers in the Zig repository are missing `stddef.h` for macOS:

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ziglang/zig%24+file:stdint.h&patternType=literal

Seeing if I can fix this so we can get `zig build test -Dtarget=aarch64-macos` passing on an M1 - so no xcode etc. is required.

**Comment by wilsonk** [comment]
Sorry about not mentioning that I had xcode installed...pretty much the first thing I do on all my Macs! Yes, it would be good to get things building without out xcode though.

**Comment by slimsag** [comment]
@wilsonk no worries :) I think I've managed to fix the upstream bug here:

https://github.com/ziglang/fetch-them-macos-headers/pull/12

**Comment by slimsag** [comment]
It turns out I just needed to compile Zig with the static flag:

https://github.com/ziglang/zig/issues/9455#issuecomment-886264636

Looks like building _without_ xcode natively on aarch64-macos, as well as cross compiling, works well!
