### ISSUE TITLE
gpu-dawn: Building on Windows - FileNotFound error in gpu-dawn build

### ISSUE THREAD

**Issue by cocoademon** [hexops/mach#315]
This may be something very obvious that I have done wrong, being completely new to Zig.

I've tried running the homepage commands on Windows, and ran into the developer mode problem.
After working around this, and also updating all the `.path`s to `.source` in the build files, I was able to compile the build file.

However, the build fails at:
```
error.Unexpected: GetLastError(267): The directory name is invalid.

... [ snip zig stdlib stuff ] ...

C:\projects\mach\gpu\libs\mach-gpu-dawn\build.zig:425:45: 0x7ff6c52a7105 in @build.gpu.libs.mach-gpu-dawn.build.getCurrentGitCommit (build.obj)
    const result = try std.ChildProcess.exec(.{
```

(I can supply full trace if necessary)

This is a CreateProcess which tries to run Git -  `git` is definitely 100% on the PATH, and I can run it from the same command line env that I'm running `zig build` from. (Although `git` is under Program Files - I haven't tried putting it in a dir with no spaces).

I know Zig historically had issues running windows programs that weren't in the CWD, but they were all closed over a year ago (eg https://github.com/ziglang/zig/issues/4120).

Is there anything obviously wrong I'm doing?

Running zig version 0.10.0-dev.2431+0e6285c8f

**Comment by cocoademon** [comment]
Addendum - putting `git` in c:\git (and updating path) makes no difference.

**Comment by d3m1gd** [comment]
i've seen similar error trying to build without git present. right now mach's build.zig doesn't produce a proper error if git is not seen by zig build.

**Comment by d3m1gd** [comment]
there is a pr #316 to check for git.
can you please try to build again when it merges?

**Comment by cocoademon** [comment]
Tried to build a minimum repro: 

```zig
fn thisDir() []const u8 {
    return std.fs.path.dirname(@src().file) orelse ".";
}

fn getCurrentGitCommit(allocator: std.mem.Allocator) ![]const u8 {
    const result = try std.ChildProcess.exec(.{
        .allocator = allocator,
        .argv = &.{ "git", "version" },
        .cwd = thisDir(),
    });
    if (result.stdout.len > 0) return result.stdout[0 .. result.stdout.len - 1]; // trim newline
    return result.stdout;
}

pub fn main() !void {
    const allocator = std.heap.page_allocator;
    const stdout = std.io.getStdOut().writer();
    const commit = try getCurrentGitCommit(allocator);
    try stdout.print("Git commit: {s}\n", .{commit});
}
```

This worked fine. Git is present and runs ok.

Made me wonder if the error was in `thisDir`, and possibly related to the Windows symlink nonsense, so I changed into the `gpu-dawn` folder and ran `zig build` - it downloaded the dawn_x86...lib.gz and headers.json.gz and appeared to complete successfully.

I'll keep poking.

**Comment by slimsag** [comment]
@cocoademon I'm pretty sure this is the issue you're running into, in the FAQ: https://github.com/hexops/mach/blob/main/doc/known-issues.md#windows-file-not-found

I am hoping to eventually eliminate all symlinks from the codebase to avoid this issue on Windows (their symlink approach is crazy bad out of the box.) Where could I have linked these docs so that you might have seen them?

**Comment by cocoademon** [comment]
@slimsag Maybe, but I followed the "developer mode" steps to fix that.

I created a minimal build using `zig init-exe` and was able to reproduce the error where `git` wasn't found on the path during build.
This appears to have been a known problem: https://github.com/ziglang/zig/issues/10561

Switching my Windows 10 Path env var to PATH instead solved it in the minimal repro, but not in the Mach project

**Comment by slimsag** [comment]
OK, makes sense, thanks for reporting this. I do think we could solve this with `std.os.realpath` - but for me this just reiterates, again, how bad/annoying symlinks are to deal with on Windows.

I'll just aim to eliminate all symlinks.

**Comment by alichraghi** [comment]
`thisDir` (`sdkPath` now) is mostly used in comptime concats, while `std.os.realpath` requires runtime computation

**Comment by slimsag** [comment]
Closing in favor of https://github.com/hexops/mach/issues/587
