### ISSUE TITLE
website: iOS display issues

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#339]

**Comment by C-BJ** [comment]
![IOS website  issue](https://user-images.githubusercontent.com/62678643/173191895-dac4d2c7-4854-4ebe-af53-932b521edd7a.jpg)

**Comment by p0d4r14n** [comment]
No issues on my iPhone 13 or iPad Pro 3rd Gen with iOS 15.5. Device/Version/Browres information would be helpful.

**Comment by slimsag** [comment]
Can't reproduce on my devices either, closing.
