### ISSUE TITLE
glfw: wayland/X11 runtime detection support (update linux system SDKs)

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#347]
GLFW now supports wayland/X11 runtime detection support. In theory we just need to turn this field to `true` by default and Mach/GLFW should work way better on Wayland systems now:

https://github.com/hexops/mach/pull/346/files#diff-e734a8f4be5ab18b5833ffdbecf5eabe92ae0d167e94977c77d0a3ba5d57e348R43

However, before we can do this we need to update the linux system SDK ([this file in specific](https://github.com/hexops/sdk-linux-x86_64/blob/main/generate-wayland.sh)) to regenerate the wayland-protocol sources matching the way GLFW now does it (since it has changed.) Something like this code: https://sourcegraph.com/github.com/glfw/glfw@d3ede7b6847b66cf30b067214b2b4b126d4c729b/-/blob/src/CMakeLists.txt?L81-93

The problem right now is various `-code.h` headers are missing.

**Comment by PiergiorgioZagaria** [comment]
Shouldn't we close this issue now?

**Comment by alichraghi** [comment]
@PiergiorgioZagaria is right. this can be closed now
