### ISSUE TITLE
freetype: need to expose mulfix or helpers to convert 26.6 pixel format to f32

### ISSUE THREAD

**Issue by mitchellh** [hexops/mach#373]
Sorry for the screenshot instead of code sample, but in trying to use this lib instead of my own bindings, I need access to the top func which uses `FT_MulFix`

<img width="857" alt="CleanShot 2022-06-27 at 09 33 03@2x" src="https://user-images.githubusercontent.com/1299/175990621-97dc2621-2076-4a10-92ff-23a1767edfb1.png">

**Comment by slimsag** [comment]
Makes sense - will try to get this added in soon (cc @alichraghi thoughts?)

I imagine we should aim to expose a good portion of https://freetype.org/freetype2/docs/reference/ft2-computations.html

**Comment by alichraghi** [comment]
Sure. I planned to support most of the following SupportAPI parts:
- [ ] [Computations](https://freetype.org/freetype2/docs/reference/ft2-computations.html)
- [ ] [List Processing](https://freetype.org/freetype2/docs/reference/ft2-list_processing.html)
- [X] [Outline Processing](https://freetype.org/freetype2/docs/reference/ft2-outline_processing.html)
- [ ] [Quick retrieval of advance values](https://freetype.org/freetype2/docs/reference/ft2-quick_advance.html)
- [ ] [Bitmap Handling](https://freetype.org/freetype2/docs/reference/ft2-bitmap_handling.html)
- [ ] [Scanline Converter](https://freetype.org/freetype2/docs/reference/ft2-raster.html)
- [ ] [Glyph Stroker](https://freetype.org/freetype2/docs/reference/ft2-glyph_stroker.html)
- [ ] [System Interface](https://freetype.org/freetype2/docs/reference/ft2-system_interface.html) ( tried zig's c allocator but it crashes )

**Comment by mitchellh** [comment]
Thanks, I'd normally be happy to contribute this myself but wasn't sure where you wanted it or how you wanted it structured. If you do want to provide guidance like that, I can fill it in.

**Comment by alichraghi** [comment]
wow, Thank you! the structure is mostly based on [freetype-rs](https://github.com/PistonDevelopers/freetype-rs/) 

### Files
lower-case files (expect [`types.zig`](https://github.com/hexops/mach-freetype/blob/main/src/freetype/types.zig) [`main.zig`](https://github.com/hexops/mach-freetype/blob/main/src/freetype/main.zig) and [`error.zig`](https://github.com/hexops/mach-freetype/blob/main/src/freetype/error.zig)) are taken from freetype headers name and Upper-case files are Structs defined in header files but they were large or contains methods so moved to a seperate file (e.g. `Face` in [`freetype.zig`](https://github.com/hexops/mach-freetype/blob/main/src/freetype/freetype.zig) or `Outline` in [`image.zig`](https://github.com/hexops/mach-freetype/blob/main/src/freetype/image.zig)).

### Types/Functions/etc
some struct has no method or complicated members. so for now they are just renamed c types (e.g `Vector = c.FT_Vector`). im just not sure if it worse to rewrite translated c functions to accept our defined types or even use `@bitCast` like before. but at the end it's just for readability.
other remaining structs is a layer over c structs:
```zig
// Face.zig
const Face = @This();

handle: c.FT_Face,

pub fn doSomething(self: Face) void {
  c.do_something(self.handle);
}
```

If you didn't find something same in binding, just do what you think is right
