### ISSUE TITLE
mach: implement gpu.Interface for WebAssembly (all wasm examples crash in App.init currently.)

### ISSUE THREAD

**Issue by jamii** [hexops/mach#378]
When reaching Device.createShaderModule from App.init, both device.ptr and device.vtable are set to 0xaaaaaaaa.

Tested in debug mode with mach b8a7c4, zig 0.10.0-dev.2785+41533fa6a, in firefox and chromium.

First step is probably for someone to verify this so we can see if it's specific to my build environment.

**Comment by slimsag** [comment]
This is expected (for now), as we have not implemented WebGPU API for WASM yet. So `device` will be undefined memory currently.

**Comment by iddev5** [comment]
GPU implementation of web is followed at: https://github.com/hexops/mach/issues/90

We should keep it to one issue.

**Comment by slimsag** [comment]
Duplicate of #90
