### ISSUE TITLE
CI: Improve jobs

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#395]
Some CI jobs aren't necessary and can be safely removed.
my claims on last 20 workflow runs:
- Sub-projects steps can be runned in the main job
- Cross-compiling in all three platform doesn't make sense anymore. Linux is also faster at cross-compiling (2x faster than windows and 1-2x compared to macOS)
- Windows and macOS jobs can just run `zig build` and `zig build test`

**Comment by slimsag** [comment]
> Sub-projects steps can be runned in the main job

Can you clarify what you mean with this?

> Cross-compiling in all three platform doesn't make sense anymore
> Windows and macOS jobs

Agreed.

**Comment by alichraghi** [comment]
> Can you clarify what you mean with this?

running `zig build test` in each sub-project in the main jobs (`x86_64-linux (.)`, `x86_64-windows (.)`, `x86_64-macos (.)`). so they will be an step instead of a job.
atm i think CI must be categorized with machine specs not sub-projects. this saves the time wasted on zig setup.
i also find this https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484/2. so we can skip testing unchanged sub-projects
