### ISSUE TITLE
build: Running sub-projects build/tests at root directory

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#396]
root build file must be able to build/test sub-projects. i think @slimsag mentioned this somewhere.
```c
build.zig // zig build test
├── glfw/build.zig
├── freetype/build.zig
├── sysaudio/build.zig
├── esc/build.zig
├── gpu/build.zig
└── sysjs/build.zig
```
possible ways:
- making tests a seperate step in *<x>/build.zig* and calling sub-projects `build` function for only build step (preferred)
- running `zig build [test]` in sub-directories

**Comment by slimsag** [comment]
Agreed.

> making tests a seperate step in /build.zig and calling sub-projects build function for only build step (preferred)

I think this is the right way.

Ideally I think that in the end, as a developer you can run the following to test each part of Mach:

1. `zig build test` run *all* tests for every project
2. `zig build test-mach` run tests for just `src/` mach code.
3. `cd subproject/ && zig build test` run tests for just a subproject
