### ISSUE TITLE
gpu-dawn binaries for x86_64-macos.11.6.6...11.6.6-none not available.

### ISSUE THREAD

**Issue by geekynils** [hexops/mach#424]
Hi there :)

I just wanted to try out mach and haven't used zig before. Here is the error I got on my Mac (Intel) is there an easy way to fix it?

```
mach 🍎 zig build run-example-boids
error: gpu-dawn binaries for x86_64-macos.11.6.6...11.6.6-none not available.
error: -> open an issue: https://github.com/hexops/mach/issues
error: -> build from source (takes 5-15 minutes):
error:        use -Ddawn-from-source=true or set `Options.from_source = true`
```

**Comment by slimsag** [comment]
Hi there!

You could use `zig build -Ddawn-from-source=true run-example-boids` and it should work, that will build Dawn from it's C++ sources. The only downside to this is it will take 5-15 minutes to complete (though should only happen like once.) The other option is to upgrade to macOS 12 Monterey.

macOS 11/Big Sur has some (minor) limitations in it's Metal graphics API, and I only have macOS 12/Monterey devices that I can personally test on at the moment - and so I made a judgement call to not support Big Sur out of the box with prebuilt binaries.

Going forward it should be easier to be more backwards compatible and support older macOS versions (the last 3, as Zig itself supports) - it's just not very easy for me to do it for macOS 11 in specific.

Hope that makes sense!

**Comment by geekynils** [comment]
Thx for the quick response. Build worked without any problem, then `example-boids` started and ran well until it ate up all my RAM (activity monitor showed ~50GB RAM or something) and I finally had to kill it! I guess there is a memory leak somewhere ...

**Comment by slimsag** [comment]
Wow that’s surprising, does it work / render otherwise?--
Follow me on twitter @slimsag <https://twitter.com/slimsag>.

**Comment by geekynils** [comment]
Sry for the late rely. Yes, apart from the memory leak it works.

**Comment by geekynils** [comment]
I updated to macOS Monterey it works, but it still continues to use more and more memory.

**Comment by kamidev** [comment]
I had the same problem, but after updating to the latest version of zig master it's gone. The fix for the memory leak was merged today.

**Comment by slimsag** [comment]
Thanks for reporting back, I'm also aware of some bugs in Dawn that will be fixed w.r.t. memory leaks on macOS by #403
