### ISSUE TITLE
dev: ci-lint.sh should run on all actions

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#432]

**Comment by alichraghi** [comment]
i did this in #429

**Comment by slimsag** [comment]
The problem is this script: https://github.com/hexops/mach/blob/main/dev/ci-lint.sh

It only runs on two files right now, I would expect it to run on [all of these](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/hexops/mach%24+file:%5C.github/workflows&patternType=literal) though
