### ISSUE TITLE
CI: windows runner cannot compile all examples ('The paging file is too small for this operation to complete.')

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#446]
Windows CI is currently failing when running `zig build compile-all`:

```
error.Unexpected: GetLastError(1455): The paging file is too small for this operation to complete.
```

**Comment by alichraghi** [comment]
for more context: https://github.com/hexops/mach/runs/7704122070?check_suite_focus=true#step:5:105
```
error: mach/gpu-dawn: prebuilt binary download failed: OutOfMemory
```

**Comment by slimsag** [comment]
Apparently that archive is empty..? Perhaps it's corrupt and Zig's gzip decompressor has a bug?

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3173176/183270865-726e3a9c-34ca-4c06-b908-4b110bb57797.png">

**Comment by Andoryuuta** [comment]
Works on windows with 7zip. The extracted file is 1.06GB:

![image](https://user-images.githubusercontent.com/8594162/183270957-d3b39e86-1578-4174-9f19-8771f38356c3.png)

**Comment by realgdman** [comment]
I've encountered same error on my desktop (windows 7). Increasing pagefile to >9 Gb helped.
Then something else prevented building, I haven't digged there yet.

**Comment by alichraghi** [comment]
We have switched to Dawn release builds by default and this doesn't happen anymore (at least on CI)
