### ISSUE TITLE
CI: macos: failures due to 'error: gpu-dawn binaries for x86_64-macos.11.6.8...11.6.8-none not available.'

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#447]
The reason why we don't have macOS 11.6 binaries is outlined in https://github.com/hexops/mach/issues/424

But CI is failing due to it currently: https://github.com/hexops/mach/runs/7658081549?check_suite_focus=true

Maybe we can just make CI run on macOS 12 ?

**Comment by slimsag** [comment]
Wait, I was confused in #424 - macOS 10 is the version I can't support, we should have working 11.6 binaries? https://github.com/hexops/mach/issues/199#issuecomment-1085306914

**Comment by alichraghi** [comment]
CI now uses macOS 12 ( e3e76b15188b4506cd276474a1fc6782803fd01f )
