### ISSUE TITLE
Is there way to use dawn as gpgpu for neural networks?

### ISSUE THREAD

**Issue by ryoppippi** [hexops/mach#452]
Just a question.
If there is a documentation for matrix or tensor computation, please let me know.
Thanks

**Comment by slimsag** [comment]
Yup, [the boids example](https://github.com/hexops/mach/tree/main/examples/boids) does general purpose compute on the GPU. There is also this excellent in-depth article of how to use the WebGPU API (same as `mach/gpu`) for GPGPU here: https://surma.dev/things/webgpu/

I'm not aware of any ML-specific docs/tutorials, you'd have to adapt that yourself, but I don't imagine it'd be hard for anyone familiar with those topics. Feel free to join the [Discord server](https://discord.gg/XNG3NZgCqp), you may find some others there interested in pushing this same topic.

**Comment by ryoppippi** [comment]
Thanks! I'll check it out!!
