### ISSUE TITLE
gpu-dawn: undefined behavior caught by UBSAN affecting Windows (dawn binary: release-777728f)

### ISSUE THREAD

**Issue by michal-z** [hexops/mach#456]
This happens only in debug builds when creating (some) graphics pipelines.
Windows 11, D3D12 backend.

```
Illegal instruction at address 0x7ff6a966b26d
D:\a\mach-gpu-dawn\mach-gpu-dawn\libs\dawn\src\dawn\native\stream\Stream.h:155:0: 0x7ff6a966b26d in awn::native::stream::Stream<D3D12_BLEND,void>::Write (dawn.lib)
D:\a\mach-gpu-dawn\mach-gpu-dawn\libs\dawn\src\dawn\native\stream\Stream.h:51:0: 0x7ff6a966b10f in awn::native::stream::StreamIn<D3D12_BLEND> (dawn.lib)
D:\a\mach-gpu-dawn\mach-gpu-dawn\libs\dawn\src\dawn\native\stream\Stream.h:74:0: 0x7ff6a966989a in awn::native::stream::StreamIn<int,int,D3D12_BLEND,D3D12_BLEND,D3D12_BLEND_OP,D3D12_BLEND,D3D12_BLEND,D3D12_BLEND_OP,D3D12_LOGIC_OP,unsigned char> (dawn.lib)
```

**Comment by slimsag** [comment]
👍 

I'll need to find an example that reproduces this, haven't tested the latest version on Windows yet so maybe one already does - not sure.

**Comment by slimsag** [comment]
FYI this could also not be a bug in Dawn but rather just be signaling passing an object with the wrong memory layout to the API (maybe something wrong in your zgpu bindings?), that's happened to a few folks in the past.

**Comment by michal-z** [comment]
Will double check but keep in mind that release build works fine.
