### ISSUE TITLE
getInstanceProcAddress can't be used with zig-vulkan

### ISSUE THREAD

**Issue by Avokadoen** [hexops/mach#49]
glfwGetInstanceProcAddress is used in [zig-vulkan](https://github.com/Snektron/vulkan-zig) to gather all function addresses required for the requested vkInstance. Here is a generated code example:

```zig
        //          v--- Loader here is glfwGetInstanceProcAddress 
        pub fn load(loader: anytype) !Self {
            var self: Self = undefined;
            inline for (std.meta.fields(Dispatch)) |field| {
                const name = @ptrCast([*:0]const u8, field.name ++ "\x00");
                const cmd_ptr = loader(.null_handle, name) orelse return error.CommandLoadFailure;
                @field(self.dispatch, field.name) = @ptrCast(field.field_type, cmd_ptr);
            }
            return self;
        }
```

In the definition of glfw.getInstanceProcAddress there are two major issues.

1. Function is inlined. This means the call convention is not transitive with zig-vulkan which expect a ``vulkan_call_conv`` which is defined as:

```zig
pub const vulkan_call_conv: std.builtin.CallingConvention = if (builtin.os.tag == .windows and builtin.cpu.arch == .i386)
    .Stdcall
else if (builtin.abi == .android and (builtin.cpu.arch.isARM() or builtin.cpu.arch.isThumb()) and std.Target.arm.featureSetHas(builtin.cpu.features, .has_v7) and builtin.cpu.arch.ptrBitWidth() == 32)
    // On Android 32-bit ARM targets, Vulkan functions use the "hardfloat"
    // calling convention, i.e. float parameters are passed in registers. This
    // is true even if the rest of the application passes floats on the stack,
    // as it does by default when compiling for the armeabi-v7a NDK ABI.
    .AAPCSVFP
else
    .C;
```
2. The returned signature does not match. mach-glfw define the return value as Error!?VKProc while glfw define it as ?VKProc

I'm unsure how this should be resolved, but two suggestions are:

- Make a builder for the function that takes a ``ABI = enum { Preserved, NotPreserved }`` where based on input enum it returns either current implementation or a true to ABI function
- Rewrite function to preserve ABI

**Comment by slimsag** [comment]
One thing I should note: The actual calling convention of this is not the same as the Vulkan calling convention you had posted in the issue description. The GLFW definition is:

```
GLFWAPI GLFWvkproc glfwGetInstanceProcAddress(VkInstance instance, const char* procname);
```

And `GLFWAPI` is defined as just:

```
/* GLFWAPI is used to declare public API functions for export
 * from the DLL / shared library / dynamic library.
 */
#if defined(_WIN32) && defined(_GLFW_BUILD_DLL)
 /* We are building GLFW as a Win32 DLL */
 #define GLFWAPI __declspec(dllexport)
#elif defined(_WIN32) && defined(GLFW_DLL)
 /* We are calling GLFW as a Win32 DLL */
 #define GLFWAPI __declspec(dllimport)
#elif defined(__GNUC__) && defined(_GLFW_BUILD_DLL)
 /* We are building GLFW as a shared / dynamic library */
 #define GLFWAPI __attribute__((visibility("default")))
#else
 /* We are building or calling GLFW as a static library */
 #define GLFWAPI
#endif
```

So, it's the C calling convention (since `_GLFW_BUILD_DLL` is false for us)

And actually if we look closely at the generate Zig code you had posted, we can also see it doesn't specify a calling convention either.

Now, having the C calling convention specified here is still a good idea (someone may want to pass this into a C library) - just thought I'd note this.

**Comment by slimsag** [comment]
Should be fixed, will sync to the mach-glfw repo later today. Also created follow-up issues for doing the same for OpenGL proc addr functions, and for investigating the comptime init idea: 

* https://github.com/hexops/mach/issues/52
* https://github.com/hexops/mach/issues/53
