### ISSUE TITLE
examples: consider restructuring examples layout in repo

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#505]
Need a longer term plan for where examples live. Unsure the main repo is the best place, maybe an external repo.

**Comment by alichraghi** [comment]
close?

**Comment by slimsag** [comment]
Fixed by:

* https://github.com/hexops/mach/commit/189997c279d8716b256502175114cdca2e9814dc
* https://github.com/hexops/mach/commit/1eba5906ae740f279dd3eb350ef1d98bd2775043
* https://github.com/hexops/mach-examples
* https://github.com/hexops/machengine.org/commit/a00efd05316fe42a6ba275e10a0e016bce9b02b3
* https://github.com/hexops/machengine.org/commit/e8a79973c379f881debb44c03211e13414b0cb11
