### ISSUE TITLE
glfw: add comptime enforcement of init

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#53]
as suggested in https://github.com/hexops/mach/issues/49#issuecomment-953944738

**Comment by slimsag** [comment]
@Avokadoen apparently your comptime init trick is relying on a compiler bug :) lol https://www.reddit.com/r/Zig/comments/qiqz5s/heres_someting_that_absolutely_blows_my_mind/hil9skv/

**Comment by Avokadoen** [comment]
Hahah that is too bad. Guess I'll look into alternatives myself. Thanks for the heads up, and sorry for the confusion!
