### ISSUE TITLE
CI: windows script doesn't add zig to path

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#556]
https://github.com/hexops/mach/actions/runs/3077928435/jobs/4973134506#step:5:1

**Comment by slimsag** [comment]
https://github.com/hexops/mach/blob/15dfb2867af90e336bed7813f8b4f5bed3a6e8ff/.github/workflows/ci.yml#L64-L67

This is because the Zig version added to the path doesn't match the Zig version downloaded. I merged a PR that was bad and it broke this. Re-running `./dev/update-zig.sh` will fix this.
