### ISSUE TITLE
proposal: FLAC decoding

### ISSUE THREAD

**Issue by desttinghim** [hexops/mach#561]
FLAC is a losslessly compressed audio format. There are two ways to get this supported: find a C library with no libc dependency and set up a build process for it, or the fun way, which is to implement it in Zig :smile:

For option one,  [mackron's dr_ libs look interesting](https://github.com/mackron/dr_libs), but I have not tried to use them.

For option two I have some notes on what needs to be figured out. [This is the specification I am referencing.](https://xiph.org/flac/format.html)
- Metadata decoding - a lot of the metadata is specific to music, so not all of it may be necessary to decode. Ideally We would expose all of the information so the developer can choose what is relevant to them
  - Stream info - Mandatory, specifies the encoding of the data
  - Seektable - Informs the decoder of the byte offset of specific frame headers useful if seeking is needed
  - Vorbis Comment - stores textual information. Might be useful
  - Cuesheet - stores offset of tracks within the file, mostly useful for storing an entire album in one file
  - Picture - FLAC files can store icons, album art, CD covers, and more. Not generally applicable to games ( unless the game developer wants to make a music player in game )
- Frames - I still need to read through this part of the Specification more thoroughly so I can understand how the audio data is actually encoded. The basic gist I've gotten is that  FLAC has a prediction function per frame and it then stores the difference between the predicted value and the actual value. All samples are processed and stored as integers to prevent floating point precision loss
  - Prediction methods
    - Verbatim - this is just PCM samples
    - Constant - TODO
    - Fixed Linear predictor - TODO
    - FIR Linear prediction - TODO
  - Residual Coding - TODO

**Comment by slimsag** [comment]
For me the big key point (for at least both flac/opus) is that we need a clear path to a reliable decoder and encoder.

dr_libs won't provide an encoder, so I think that's an arguably worse option.

I would love a pure-Zig encoder+decoder, but it seems pretty complex/involved to pull off. I won't have time for it personally, and I imagine there's a lot of stuff to handle here. Easy to make one that works okay, but hard to make one that's reliable etc. If you think you're up for the task, I'd love to see that happen.

If it was me personally, I would go for making `zig build` build libFLAC (which is permissively licensed, https://github.com/xiph/flac ) and vendoring the minimal set of C sources we need for that + exposing a nice set of bindings to it. Hard to beat the reliability/performance of that implementation.

**Comment by desttinghim** [comment]
I'd like to implement FLAC in zig, but I think for now I'll try and get libFLAC building. I can circle back to implementing a native zig FLAC library later. Otherwise I'll spend too much time reimplementing everything with nothing to show 😅

**Comment by desttinghim** [comment]
I've gotten libFLAC building with Zig. I haven't made any zig bindings yet but using just the encoder and decoder modules without the metadata module seems to build on `wasm32-freestanding-musl`. The next step for me is to vendor the sources instead of using a git submodule. After that is tweaking the library code. libFLAC already has a reasonable API for avoiding a dependence on fopen, but the fopen code is mixed in with the other code.

For the zig API, I'm thinking of lightly wrapping the callback API to use slices and zig errors. Anything higher level should probably go into sysaudio.

**Comment by meshula** [comment]
I took the trouble to make a minimal "unity" build script for FLAC for libnyquist:

https://github.com/ddiakopoulos/libnyquist/blob/master/src/FlacDependencies.c

very easy to translate to zig build, and I already worked out file ordering and so on to pull off the build in one step :)

I did it for Orbus and others as well ~

https://github.com/ddiakopoulos/libnyquist/tree/master/src

There's more tricks in the main cmake file https://github.com/ddiakopoulos/libnyquist/blob/master/CMakeLists.txt

libnyquist can open just about any format you can think of, and was another one of those "takes forever to build" projects that was reducible to just a few seconds through unity-build tricks.

**Comment by desttinghim** [comment]
I think I had most of the flags set for FLAC, but this looks very useful! Thank you.

**Comment by slimsag** [comment]
Sounds good to me 👍 

And just to clarify, I'm happy to have this directly in `libs/flac` of this repository.

**Comment by slimsag** [comment]
https://github.com/hexops/mach-flac now exists; but with a caveat https://github.com/hexops/mach/issues/888
