### ISSUE TITLE
machlibs/imgui: confirm bindings work on windows/linux

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#593]
Confirm this library by @SergeiSomin works on every OS: https://github.com/machlibs/imgui

* [x] macOS
* [x] Linux (@alichraghi reports it working on Linux, @renerocksai reports an issue with i3 WM?)
* [x] Windows

**Comment by renerocksai** [comment]
* [x]  Linux (@renerocksai on Linux with i3)
