### ISSUE TITLE
mach: setOptions API needs a better "update" approach

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#623]
As it stands today, usage like:

```
core.setOptions(.{.vsync = .double});
```

Is almost always incorrect, because it means you are resetting all other options to their defaults. The correct version would be:

```
var options = core.options;
options.vsync = .double;
core.setOptions(options);
```

We should:

1. Make `core.setOption(.vsync, .double)` a thing, inform users that `setOptions` (plural) is probably not what they want.
2. For the C ABI, document this quirk or something, suggest languages wrapping our C API to implement a `setOption` API of their own or something.

**Comment by alichraghi** [comment]
`core.setVsync` looks cleaner IMO

**Comment by slimsag** [comment]
Note: may need to consider `core.setTItle` instead of `core.setOption(.title, "foo")` because we need a way to confirm the option setting doesn't affect other settings. For example, `core.setOption(.title, "foo")` after the window has been resized by the user would affect its size.

**Comment by slimsag** [comment]
Decision: use `core.setVSync`, `core.setTitle`, etc. style
