### ISSUE TITLE
sysaudio: document that libasound2, pulseaudio, and jack are required to be installed; load them dynamically

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#649]
1. [ ] Right now we `sudo apt install libasound2-dev` in our CI pipelines, we should replace this with just `libasound2` to ensure we do not accidently rely on headers in that package. i.e. we currently only depend on `libasound2.so` being available on the system.
2. [ ] We should add to docs a note that `libasound2` must be installed/present on systems where Mach is to run with sysaudio.
3. [ ] Really ideally, we should load libasound2 dynamically at runtime so that if it is not present on a users system we can provide a nice error and fallback to other audio backends (or none at all.)

**Comment by slimsag** [comment]
Looks like it's an issue for pulseaudio and jack libraries too.

**Comment by slimsag** [comment]
Tips for fixing the 'load these libraries dynamically':

1. Run this sysaudio example: https://github.com/hexops/mach/tree/b8deaf801040aebd0f0c117e14f6af7796e08b98/libs/sysaudio/examples
3. Remove these 3 link library lines one at a time:

https://github.com/hexops/mach/blob/b8deaf801040aebd0f0c117e14f6af7796e08b98/libs/sysaudio/sdk.zig#L36-L38

4. After removing one, rerun the example. The compiler will give you warnings about which functions from these libraries are not found / linked to.
5. Search the codebase for where we call those functions, and instead replace them with a call to a dynamic library using `std.DynLib` (see e.g. example code here: https://github.com/ziglang/zig/blob/master/lib/std/dynamic_library.zig#L392-L404)

**Comment by leelavg** [comment]
- It can't be this simple right?
``` diff
diff --git a/libs/sysaudio/sdk.zig b/libs/sysaudio/sdk.zig
index fe6ec74..982e397 100644
--- a/libs/sysaudio/sdk.zig
+++ b/libs/sysaudio/sdk.zig
@@ -33,9 +33,9 @@ pub fn Sdk(comptime deps: anytype) type {
                     step.linkFramework("CoreFoundation");
                     step.linkFramework("CoreAudio");
                 } else if (step.target.toTarget().os.tag == .linux) {
-                    step.linkSystemLibrary("asound");
-                    step.linkSystemLibrary("pulse");
-                    step.linkSystemLibrary("jack");
+                    step.linkSystemLibraryName("asound");
+                    step.linkSystemLibraryName("pulse");
+                    step.linkSystemLibraryName("jack");
                     step.linkLibC();
                 }
             }
```
- system_sdk is being linked in `deps.system_sdk.include(b, step, .{});` and we just need to find the shared lib there
- I'm definitely missing something, some hints are appreciated

---

- as `std.DynLib.open` takes a path, is there anyway to get known folders for linux where shared libs exists?
- this is also in-correct right?
``` diff
$ gd
diff --git a/libs/sysaudio/sdk.zig b/libs/sysaudio/sdk.zig
index fe6ec74..beb26ac 100644
--- a/libs/sysaudio/sdk.zig
+++ b/libs/sysaudio/sdk.zig
@@ -33,7 +33,7 @@ pub fn Sdk(comptime deps: anytype) type {
                     step.linkFramework("CoreFoundation");
                     step.linkFramework("CoreAudio");
                 } else if (step.target.toTarget().os.tag == .linux) {
-                    step.linkSystemLibrary("asound");
+                    // step.linkSystemLibrary("asound");
                     step.linkSystemLibrary("pulse");
                     step.linkSystemLibrary("jack");
                     step.linkLibC();
diff --git a/libs/sysaudio/src/alsa.zig b/libs/sysaudio/src/alsa.zig
index 43ea52a..c06424b 100644
--- a/libs/sysaudio/src/alsa.zig
+++ b/libs/sysaudio/src/alsa.zig
@@ -1,5 +1,5 @@
 const std = @import("std");
-const c = @cImport(@cInclude("alsa/asoundlib.h"));
+const c = std.DynLib.open("libasound.so");
 const main = @import("main.zig");
 const backends = @import("backends.zig");
 const util = @import("util.zig");
```
- hitting this
```
error: comptime call of extern function                                                 
            .handle = system.dlopen(path_c, system.RTLD.LAZY) orelse {
```
- pls let me know what should be read before fixing this issue, thanks in advance.

**Comment by slimsag** [comment]
> system_sdk is being linked in `deps.system_sdk.include(b, step, .{});` and we just need to find the shared lib there

No, the point is that once this issue is fixed we shouldn't need them to be in the system SDK at all. The program won't link against them at all, but instead will find them at runtime using `std.DynLib.open` In the end the only line that should remain there is `step.linkLibC();`

> as std.DynLib.open takes a path, is there anyway to get known folders for linux where shared libs exists?

I am pretty sure that just e.g. `libasound.so` may be passed.

> error: comptime call of extern function                                                 
>            .handle = system.dlopen(path_c, system.RTLD.LAZY) orelse {

We will need to do something like:

```
var lib = try std.DynLib.open("libasound.so");
```

Then ask it for the function signatures we want like e.g. if we wanted an `Add` function out of the library:

```
    const Add = *const fn (i32, i32) callconv(.C) i32;
    const addFn = lib.lookup(Add, "add") orelse return error.SymbolNotFound;
```

From there we could call `addFn` - we might also want to close the library when we're finally done with it maybe:

```
lib.close();
```

**Comment by leelavg** [comment]
- thanks a lot for the explanation, I'll give it another try at the earliest!

**Comment by slimsag** [comment]
@leelavg no worries, if there are any questions I can answer to help with whatever you need to learn let me know :) I'm always happy to help, don't be afraid to ask questions :) feel free to ask in the #development channel in Discord too since we can go back and forth there a bit easier

**Comment by Cloudef** [comment]
https://github.com/tinyalsa/tinyalsa something you can also use if you want to get rid of libasound dep
