### ISSUE TITLE
root struct of file 'std' has no member named 'Build'

### ISSUE THREAD

**Issue by yds12** [hexops/mach#743]
I followed exactly the instructions:

```
git clone --recursive https://github.com/hexops/mach-examples
cd mach-examples/
zig build run-boids
```

But I get this error:

```
<...>/mach-examples/build.zig:6:21: error: root struct of file 'std' has no member named 'Build'
pub fn build(b: *std.Build) !void {
                 ~~~^~~~~~
referenced by:
    runBuild: <...>/zig-linux-x86_64-0.11.0-dev.229+adc3fafbc/lib/build_runner.zig:229:45
    usage__anon_5129: <...>/zig-linux-x86_64-0.11.0-dev.229+adc3fafbc/lib/build_runner.zig:240:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

I'm using zig version `0.11.0-dev.229+adc3fafbc`.

Am I doing something wrong? Sorry for the possibly ignorant question, I'm totally new to zig.

**Comment by alichraghi** [comment]
your zig version is too old. update it

**Comment by yds12** [comment]
Thanks, solved!

**Comment by slimsag** [comment]
Glad to hear it :) thanks for pointing in the right direction @alichraghi - and feel free to join the discord @yds12 - we're always happy to help :) let me know if I can do anything to make your experience better!

**Comment by JJ** [comment]
> your zig version is too old. update it

I'm getting the same error with zig 0.13.0. Might be the *code* is too old? In that case, what's the solution?

**Comment by slimsag** [comment]
You need a specific zig version, check the website. 0.13.0 is not a supported version.

**Comment by SkibidiGestapoRizz** [comment]
Which version?

**Comment by codetinkerhack** [comment]
Getting it on  zig version
0.14.0-dev.2577+271452d22
