### ISSUE TITLE
binary release be8c48e of mach-gpu-dawn have no headers.json.gz

### ISSUE THREAD

**Issue by Dimandragon** [hexops/mach#764]
there is no headers.json.gz file in https://github.com/hexops/mach-gpu-dawn/releases/tag/release-be8c48e

**Comment by slimsag** [comment]
Should be fixed now, I've reverted the bad commit temporarily. headers.json.gz is built by our macOS M1 github actions runner and it looks like it failed for some reason, I'll debug later
