### ISSUE TITLE
mach-examples is invalid to build

### ISSUE THREAD

**Issue by Dimandragon** [hexops/mach#768]
on my laptop (windows, x64) i can't build mach-examples

after `$ git clone --recursive https://github.com/hexops/mach-examples`, `$ cd mach-examples/` and `zig build` or `zig build "some text"` a get this massage

`error: EndOfStream`

**Comment by alichraghi** [comment]
update your zig

**Comment by Dimandragon** [comment]
> update your zig

thank, it have help me
