### ISSUE TITLE
glfw: add support for cross-compiling for Wayland

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#77]
Reported by @AliChraghi in https://github.com/hexops/mach/issues/75#issuecomment-969446408

we will need to add the right apt packages to the fetch.sh script here so our SDK has the headers/libs so we can cross compile for Wayland. https://github.com/hexops/sdk-linux-x86_64

It is worth noting that it may be worth waiting until GLFW's Wayland backend (which today is still very immature I think) improves, e.g. in the next version of GLFW there will be support for choosing between X11 and Wayland backends at runtime and so we should begin building for both by default. glfw/glfw#1958

**Comment by AliChraghi** [comment]
i think [this a useful resource](https://github.com/go-gl/glfw/pull/315) to fix this
