### ISSUE TITLE
glfw: found test declaration with duplicate name: test.pollEvents

### ISSUE THREAD

**Issue by Tekkunsan** [hexops/mach#777]
Zig Version: 0.11.0-dev.3045
It's easy to fix, just delete the duplicate `test.pollEvents` but they are not identical

``` Zig
test "pollEvents" {
    init(.{ .cocoa_chdir_resources = true });
    if (getErrorString()) |err| {
        std.log.err("failed to initialize GLFW: {?s}", .{err});
        std.process.exit(1);
    }
    defer terminate();
}

test "pollEvents" {
    defer clearError(); // clear any error we generate
    if (!init(.{})) {
        std.log.err("failed to initialize GLFW: {?s}", .{getErrorString()});
        std.process.exit(1);
    }
    defer terminate();

    pollEvents();
}
```

**Comment by slimsag** [comment]
Fixed by https://github.com/hexops/mach/pull/779 - if you still encounter issues let me know. You may want to try the [supported Zig version](https://github.com/hexops/mach#supported-zig-version) - which can sometimes be behind latest nightly by a few weeks.
