### ISSUE TITLE
gpu-dawn: add support for x86_64-windows-msvc

### ISSUE THREAD

**Issue by mlarouche** [hexops/mach#786]
Using `mach-examples` repository

```shell
❯ zig build -Dtarget=native-native-msvc -Ddawn-from-source=true
error: gpu-dawn binaries for x86_64-windows.win10_fe...win10_fe-msvc not available.
error: -> open an issue: https://github.com/hexops/mach/issues
error: -> build from source (takes 5-15 minutes):
error:        use -Ddawn-from-source=true or set `Options.from_source = true`
```

The main reason for adding MSVC ABI support: being able to use closed-source libraries that has been compiled with Visual Studio.

**Comment by slimsag** [comment]
I'm very interested in MSVC support as well, however with Dawn (specifically, DirectXShaderCompiler) it's not so simple to fix/support from what I recall when attempting to support it about a year ago.

I'm sure it can be sorted out, will just require a bit of munging / grunt work.

**Comment by slimsag** [comment]
https://github.com/hexops/mach/issues/1166#issuecomment-2212990680
