### ISSUE TITLE
example bug: core-imgui mouse position is different

### ISSUE THREAD

**Issue by funatsufumiya** [hexops/mach#802]
I tried core-imgui example on https://github.com/hexops/mach-examples/commit/06d38364cbc4459baf3ce9c14a27507ad2ecd671, mouse pointing position is weird. Probably scaling problem. (see the screenshot movie below)

https://github.com/hexops/mach/assets/3406260/4d95bb48-03e9-4d12-bd29-294276493005

Apple M1, Metal driver on macOS Version 13.4 (Build 22F66), MacBook Air M1 2020, Zig 0.11.0-dev.3329+1ab008d89

**Comment by funatsufumiya** [comment]
I tried changing screen resolutions on system settings, but any of them solved this problem.

<img width="715" alt="Screenshot 2023-06-07 at 16 48 00" src="https://github.com/hexops/mach/assets/3406260/0515cc4b-d704-4f0f-a47d-26a397505e7a">

**Comment by lhk** [comment]
This would be quite interesting to me as well.
I'm searching for a game or UI framework to tinker on a side project with zig and was looking at mach to run zgui with webgpu.

**Comment by lhk** [comment]
just tried, I have the same issue.
Freshly cloning mach examples, zig is at version `0.11.0-dev.3395+1e7dcaa3a` and I'm running `zig build run-core-imgui`.
My system is Macos 13.4 M1 macbook air.

**Comment by slimsag** [comment]
I plan to remove imgui support in favor of a custom GUI solution. https://github.com/hexops/mach/issues/802
