### ISSUE TITLE
`math.max`/`math.min`/`builtin.Version` deprecated

### ISSUE THREAD

**Issue by alichraghi** [hexops/mach#811]
### https://github.com/ziglang/zig/pull/16025

**TO REMOVE: https://sourcegraph.com/search?q=context:global+-repo:dusk+repo:%5Egithub%5C.com/hexops/+lang:Zig+math.max%28+OR+math.min%28+OR+%22+min%28%22+OR+%22+max%28%22+OR+builtin.Version&patternType=standard&sm=1&groupBy=repo**

```
std.math.max -> @max
std.math.min -> @min
std.builtin.Version -> std.SemanticVersion
```

final boss: https://github.com/ziglang/zig/pull/16046

**Comment by LaPingvino** [comment]
[SemanticVersion.zip](https://github.com/hexops/mach/files/11811149/SemanticVersion.zip)
Somehow Github refuses the .patch file if I don't zip it, but #194 shows fixed after applying this patch for the SemanticVersion thing

**Comment by slimsag** [comment]
Mind sending a PR?

**Comment by LaPingvino** [comment]
Created #815

**Comment by slimsag** [comment]
https://github.com/hexops/mach/commit/c62bae6edcf00322d5b2b87bb5c72985813016a5

examples will get updated soon, closing.
