### ISSUE TITLE
glfw: Leftover errdefer in glfw.init

### ISSUE THREAD

**Issue by Luexa** [hexops/mach#826]
https://github.com/hexops/mach/blob/5cf18801a180859bda446347f424f4af9ff23430/libs/glfw/src/main.zig#L92-L98

The `errdefer` here will not trigger as `glfw.init()` returns a bool, not an error union. This means that the assert will be incorrectly triggered if `glfw.init()` is invoked after a previous invocation of `glfw.init()` returned false. Some other mechanism is required to unset the debug value.

Also, `glfw.terminate()` shouldn't need to assert that GLFW is initialized, as `glfwTerminate()` has well defined behavior of doing nothing when `glfwInit()` has not returned successfully. Of course, the debug value should still be unset on `glfw.terminate()`.

**Comment by slimsag** [comment]
https://github.com/hexops/mach/issues/1166#issuecomment-2212962722
