### ISSUE TITLE
docs: broken link

### ISSUE THREAD

**Issue by jmrico01** [hexops/mach#841]
The very first link to "examples" in [the Getting started page](https://machengine.org/next/core/getting-started/) is broken. Would have PR'd it but I couldn't find it in https://github.com/hexops/machengine.org.

**Comment by slimsag** [comment]
Thanks! Will fix. The unreleased website lives in the `next` branch

**Comment by HeCorr** [comment]
Fixed in https://github.com/hexops/machengine.org/commit/960a9a92428e92bd7b986493110fb7b077067d93
