### ISSUE TITLE
core: linux: MangoHud reports using both OpenGL and Vulkan when `MACH_GPU_BACKEND=opengl`; is our OpenGL init code correct?

### ISSUE THREAD

**Issue by anyputer** [hexops/mach#860]
MangoHud says it's using Vulkan, and RenderDoc says there are two distinct windows, and I can't capture the OpenGL window. vkBasalt post-processing working makes it clear that it's actually using Vulkan to render, and OpenGL fails somehow.

![Screenshot from 2023-07-15 21-25-40](https://github.com/hexops/mach/assets/32988993/d2f8db23-0e38-42d4-87a0-ff0fc4dcb8be)

**Comment by slimsag** [comment]
Notes to self on how to reproduce this:

I assume I would need to e.g. install MangoHud https://github.com/flightlessmango/MangoHud

And then run e.g. the textured-cube example like this with `MACH_GPU_BACKEND=opengl`:

```
git clone --recursive https://github.com/hexops/mach-core
cd mach-core/
MACH_GPU_BACKEND=opengl zig build run-textured-cube
```

And then see if we can reproduce the same 'both are in use' behavior.
