### ISSUE TITLE
The README has a few lines for getting started, but it doesn't work.

### ISSUE THREAD

**Issue by 7ombie** [hexops/mach#862]
The README says to do this:

``` sh
git clone --recursive https://github.com/hexops/mach-examples
cd mach-examples
zig build run-core-boids
```

When I tried that, `zig build` failed...

``` sh
/Users/carl/Projects/mach-examples/libs/mach/libs/mach-gpu-dawn/build.zig:259:68: error: expected type 'builtin.Version', found 'SemanticVersion'
            const order = target.os.version_range.semver.min.order(min_available);
                                                                   ^~~~~~~~~~~~~
/Users/carl/Vendor/Zig/lib/std/SemanticVersion.zig:1:1: note: struct declared here
//! A software version formatted according to the Semantic Version 2 specification.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/carl/Vendor/Zig/lib/std/builtin.zig:488:21: note: struct declared here
pub const Version = struct {
                    ^~~~~~
/Users/carl/Vendor/Zig/lib/std/builtin.zig:512:37: note: parameter type declared here
    pub fn order(lhs: Version, rhs: Version) std.math.Order {
                                    ^~~~~~~
referenced by:
    link: /Users/carl/Projects/mach-examples/libs/mach/libs/mach-gpu-dawn/build.zig:108:9
    link: /Users/carl/Projects/mach-examples/libs/mach/libs/mach-gpu/build.zig:92:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

/Users/carl/.cache/zig/p/122044a43c075d9357bff82ab66358e95e29ef01197fcb8c650489abd83511e41d2f/build.zig:34:38: error: expected struct or union; found '[]const u8'
            .source_dir = .{ .path = "encoder" },
                                     ^~~~~~~~~
```

I clicked on the *Known Issues* link, but that's a 404.

I'm on macOS (ARM), using Zig 0.11.0.

**Comment by g012** [comment]
It's worse for me:

`zig build run-core-boids
no step named 'run-core-boids'. Access the help menu with 'zig build -h'
error: the following build command failed with exit code 1:
/Users/g012/data/mach-examples/zig-cache/o/14e3642d84c89388ffae5c5337cc23d5/build /Users/g012/bin/zig-macos-x86_64-0.11.0-dev.4059+17255bed4/zig /Users/g012/data/mach-examples /Users/g012/data/mach-examples/zig-cache /Users/g012/.cache/zig run-core-boids`

I happily did it and tried `zig build run-sprite2d`:

`Build Summary: 18/23 steps succeeded; 1 failed (disable with --summary none)
run-sprite2d transitive failure
└─ run sprite2d transitive failure
   ├─ zig build-exe sprite2d Debug native 1 errors
   └─ sprite2d transitive failure
      └─ install sprite2d transitive failure
         └─ zig build-exe sprite2d Debug native (+13 more reused dependencies)
libs/mach/src/math.zig:77:16: error: expected 1 argument, found 2
        return @splat(size(V), scalar);`
        
Using the latest binary release from zig website: `zig version
0.11.0-dev.4059+17255bed4`

**Comment by alichraghi** [comment]
@g012 mach-core examples are moved into https://github.com/hexops/mach-core

**Comment by g012** [comment]
> @g012 mach-core examples are moved into https://github.com/hexops/mach-core

Thanks, I've tried and triangle, triangle-msaa, boids work, but this one has the same build error on @splat :

```Build Summary: 15/20 steps succeeded; 1 failed (disable with --summary none)
run-pixel-post-process transitive failure
└─ run pixel-post-process transitive failure
   ├─ zig build-exe pixel-post-process Debug native 7 errors
   └─ pixel-post-process transitive failure
      └─ install pixel-post-process transitive failure
         └─ zig build-exe pixel-post-process Debug native (+13 more reused dependencies)
examples/libs/zmath/src/zmath.zig:335:12: error: expected 1 argument, found 2
    return @splat(veclen(T), value);
           ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by slimsag** [comment]
Thanks for reporting, I'm working on fixing this and updating all our docs more generally.

You may find this doc helpful in specific: https://machengine.org/next/core/getting-started/

Closing in favor of #881 which is more broad
