### ISSUE TITLE
opus: add mach-opus audio file decoding/encoding library using libopus

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#871]

**Comment by meshula** [comment]
Repeat comment from the FLAC issue, just adding for completeness.

If it's useful as reference, I wrote cmake scripts, which are trivially portable to build.zig to build all the major audio encoding/decoding libraries here https://github.com/ddiakopoulos/libnyquist/blob/master/CMakeLists.txt

I went to the trouble of working out the actual set of necessary files to include, as many of these audio codec libraries are .... unnecessarily complicated.

The top level libnyquist interfaces have stood the test of time to abstract audio file loading, in case there's any useful inspiration there.
