### ISSUE TITLE
flac: add mach-flac audio file decoding/encoding library using libflac

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#872]

**Comment by meshula** [comment]
If it's useful as reference, I wrote cmake scripts, which are trivially portable to build.zig to build all the major audio encoding/decoding libraries here https://github.com/ddiakopoulos/libnyquist/blob/master/CMakeLists.txt

I went to the trouble of working out the actual set of necessary files to include, as many of these audio codec libraries are .... unnecessarily complicated.

The top level libnyquist interfaces have stood the test of time to abstract audio file loading, in case there's any useful inspiration there.

**Comment by slimsag** [comment]
https://github.com/hexops/mach-flac now exists; but there's some known follow-up work to be done https://github.com/hexops/mach/issues/888
