### ISSUE TITLE
docs: we need some way to detect broken links on machengine.org

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#873]
I would really appreciate any suggestions for software that can do this, open source or not, so that I don't have to write this myself.

We need something that crawls machengine.org and looks for broken links, and reports them to me to fix.

**Comment by C-BJ** [comment]
Do you just want to check the markdown link in the website source code
If so, you can try https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by slimsag** [comment]
Wrench will now automatically scan machengine.org for broken links every day, including links to external websites; and will keep a github issue with all the details up-to-date for us. https://github.com/hexops/mach/issues/886 Some very useful insights already 🙂

<img width="852" alt="image" src="https://github.com/hexops/mach/assets/3173176/ebafcf4b-cedb-4e79-8486-fc3263ac1eac">

(ended up using https://github.com/raviqqe/muffet which scans the actual HTML and external links, not just markdown; plus it's written in Go / not a terrifying npm project)
