### ISSUE TITLE
glfw: Readme has wrong package installation instructions

### ISSUE THREAD

**Issue by nothke** [hexops/mach#882]
I'm new to zig package manager and so I'm not sure exactly yet how to use it, especially because there have been so many changes in short time. The [mach-glfw](https://github.com/hexops/mach-glfw#adding-dependency) docs mention you should add this to your build:

```zig
exe.addModule("glfw", glfw.module(b));
try glfw.link(b, exe, .{});
```
But .module(b) and .link have been removed in a recent commit.

What is the correct way to use mach-glfw as a package?

**Comment by slimsag** [comment]
Sorry for the late reply.

Closing in favor of #881 (which also has instructions on how to use the latest version.) I'm working on getting docs updated.
