### ISSUE TITLE
core: `zig build run` does not output and run from `zig-out/bin` 

### ISSUE THREAD

**Issue by foxnne** [hexops/mach#883]
Building examples or projects dependent on `mach-core` does not build to `zig-out/bin`, which means projects with assets that are not embedded will not be found searching for a relative path unless we change the `cwd` to the executable location. However, if we do that, now `zig build run` will be running from the cache, making the file paths broken as well.

[Discussion on Discord](https://discord.com/channels/996677443681267802/1133961940985729136/1133961940985729136)

**Comment by xdBronch** [comment]
hexops/mach-core/pull/18 related but doesnt completely solve
