### ISSUE TITLE
basisu: package stability

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#965]
This is a tracking issue for declaring the mach-opus package as stable. This means:

1. [ ] It is in use inside Mach engine and we feel good about it overall.
2. [ ] None of the [outstanding issues](https://github.com/hexops/mach/labels/basisu) are of major concern.
3. [ ] The README and website have been updated to remove the experimental warning.

**Comment by IsaacMcCracken** [comment]
What are some tasks that need to be done to feel good about it and have it become a part of mach engine?

**Comment by slimsag** [comment]
I no longer feel confident in basisu being the right long-term direction, as a result it is no longer an official mach project. We need to look at GPU texture compression with a fresh set of eyes.

The code remains at https://github.com/slimsag/mach-basisu
