### ISSUE TITLE
ecs: package stability

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#968]
**mach-ecs is very very experimental and not ready for general use.**

This is a tracking issue for declaring the mach-ecs package as stable. This means:

1. [ ] It is in use inside Mach engine and we feel good about it overall.
2. [ ] None of the [outstanding issues](https://github.com/hexops/mach/labels/ecs) are of major concern.
3. [ ] The README and website have been updated to remove the experimental warning.

**Comment by shayded-exe** [comment]
Just curious, what is the rough estimate of when it will be just "experimental" instead of "very very experimental"?
