### ISSUE TITLE
harfbuzz: GlyphPosition is missing a private field

### ISSUE THREAD

**Issue by dcov** [hexops/mach#993]
This was mentioned in the discord by someone else, it's missing the `var` field: https://github.com/harfbuzz/harfbuzz/blob/970d2c438f849700b879d76e8c183c2edfbaccdb/src/hb-buffer.h#L191

It's a one line fix, which I can easily do, or whatever is easiest for you.

**Comment by slimsag** [comment]
Thanks for filing this @dcov ! Would you mind sending a PR? Otherwise I'll try to get to it soon

**Comment by slimsag** [comment]
Fixed by https://github.com/hexops/mach-freetype/pull/22

**Comment by dcov** [comment]
I should've checked back sooner haha sorry.

For future reference, I should file PRs under the specific repo right? So this one would've been under the `mach-freetype` repo correct?

@slimsag

**Comment by alichraghi** [comment]
yes. mach doesn't follow monorepo strategy anymore

**Comment by slimsag** [comment]
Not sure what you mean?

PRs are sent to whatever repository the code exists in (you literally can't send them anywhere else, the code only exists in one place)

Issues are filed here in this repository (there's nowhere else to file them, so it should be very difficult to get confused here)

Hope that helps :)
